#!/usr/bin/env python3
"""Self-contained, forge-loop-format driver for mxfp8_grouped_gemm (MERGED single file).

ONE file that combines what the Arena suite normally splits across
``scripts/task_runner.py`` (operator contract: cases, _make/_run/_reference,
graph-timed benchmark) and ``scripts/forge_driver.py`` (the forge-loop CLI
contract: ``--profile-run`` / ``--bench-mode`` / ``allclose:`` / ``case_ms:`` /
``mean_ms:``), with ``session_cases.json`` inlined as ``_SESSION_CASES_JSON`` --
so it needs NO sibling files.

It is a drop-in for ``scripts/forge_driver.py``: forge-loop copies the task's
``scripts/forge_driver.py`` verbatim to the workspace root and runs
``python forge_driver.py <args>`` reading only stdout. To have forge-loop use
THIS merged file, place it at ``scripts/forge_driver.py`` (it is a strict
superset of the thin delegator). ``WORKSPACE`` is resolved robustly so it works
whether it runs from the task ``scripts/`` dir (Arena) or the workspace root
(the forge copy).

AUTO-GENERATED by merging task_runner.py + forge_driver.py; do not hand-edit --
regenerate from those two files instead.
"""
from __future__ import annotations

import argparse
import importlib
import importlib.util
import json
import os
import sys
from pathlib import Path



import argparse
import json
import os
import sys
from pathlib import Path

_SESSION_CASES_JSON = r"""{
  "source_day": "2026-07-23",
  "date_field": "model_config (live MoE routing capture was empty)",
  "platform": "MI355X/gfx950",
  "framework": "sglang origin/main MXFP8 (v0.5.12-rocm720-mi35x)",
  "base_image": "harbor.crusoe.primus-safe.amd.com/proxy/primussafe/sglang:v0.5.12-rocm720-mi35x-profilerfix",
  "model": "MiniMax-M3-MXFP8",
  "session_id": "17520246-e676-42be-83b4-6741291d723f",
  "operator": "mxfp8_grouped_gemm",
  "kernel": "_mxfp8_grouped_gemm_kernel",
  "timed_callable": "_grouped_gemm_mxfp8 (GEMM1 a_div=top_k + GEMM2 a_div=1)",
  "task_name": "mi355x-sg-mxfp8-grouped-gemm",
  "gpu_pct": 23.75,
  "profile": {
    "total_ms": 592.0725,
    "pct_gpu_time": 23.75
  },
  "quant": {
    "scheme": "mxfp8_ocp_1x32_e8m0",
    "operand_dtype": "float8_e4m3fn",
    "scale_dtype": "uint8_e8m0",
    "block_size": [1, 32],
    "out_dtype": "bfloat16",
    "accumulate": "fp32",
    "activation": "swiglu_oai (split, gated silu; alpha=1.702, beta=1.0, limit=7.0)"
  },
  "provenance": "MoE routing is value-dependent so the live-server GEAK capture produced no oracle (empty _capture). Dims are derived from model config.json: hidden_size=6144, intermediate_size=3072 (TP=8 -> per-rank 384), num_local_experts=128, num_experts_per_tok=4, quant mxfp8 weight_block_size=[1,32]. Token buckets T: decode {1,64}, prefill {16384} from the linear-kernel meta.json regime for the same session. M_routed = T*top_k.",
  "params_common": {
    "hidden": 6144,
    "inter": 384,
    "experts": 128,
    "top_k": 4,
    "alpha": 1.702,
    "beta": 1.0,
    "limit": 7.0
  },
  "cases": [
    {
      "id": "decode-t1",
      "regime": "decode",
      "params": {"tokens": 1, "hidden": 6144, "inter": 384, "experts": 128, "top_k": 4,
                 "alpha": 1.702, "beta": 1.0, "limit": 7.0, "max_relerr": 0.08}
    },
    {
      "id": "decode-t64",
      "regime": "decode",
      "params": {"tokens": 64, "hidden": 6144, "inter": 384, "experts": 128, "top_k": 4,
                 "alpha": 1.702, "beta": 1.0, "limit": 7.0, "max_relerr": 0.08}
    },
    {
      "id": "prefill-t16384",
      "regime": "prefill",
      "params": {"tokens": 16384, "hidden": 6144, "inter": 384, "experts": 128, "top_k": 4,
                 "alpha": 1.702, "beta": 1.0, "limit": 7.0, "max_relerr": 0.08}
    }
  ]
}
"""


def _resolve_workspace() -> Path:
    """Workspace root whether this file runs from the task ``scripts/`` dir
    (Arena) or from the workspace root (the copy forge-loop makes). Anchored on
    the always-present ``config.yaml``."""
    here = Path(__file__).resolve().parent
    for cand in (here.parent, here):
        if (cand / "config.yaml").is_file():
            return cand
    return here.parent


WORKSPACE = _resolve_workspace()
SPEC = json.loads(_SESSION_CASES_JSON)
CASES = SPEC["cases"]
BLOCK_M = 64
# Token count for the compile smoke test only. Correctness and performance both
# run at the scored token count; the reference is batched per expert, so a full
# shape stays affordable.
COMPILE_SMOKE_MAX_TOKENS = 64


def _configure() -> None:
    os.environ.setdefault("USER", "agentkernelarena")
    os.environ.setdefault("LOGNAME", "agentkernelarena")
    for key in ("GPU_ARCHS", "PYTORCH_ROCM_ARCH", "AMDGPU_TARGETS", "GPU_TARGETS"):
        os.environ.setdefault(key, "gfx950")
    seeded = WORKSPACE / "sglang"
    if (seeded / "__init__.py").is_file():
        sys.path.insert(0, str(WORKSPACE))
    else:
        sys.path.insert(0, os.environ.get("SGLANG_PYTHON", "/sgl-workspace/sglang/python"))
    os.chdir(WORKSPACE)


def _torch():
    import torch

    if not torch.cuda.is_available():
        raise RuntimeError("ROCm GPU (gfx950) is required")
    return torch


def _relerr(a, b) -> float:
    a = a.float()
    b = b.float()
    return float(((a - b).norm() / (b.norm() + 1e-8)).item())


# --------------------------------------------------------------------------- #
# CUDA-graph benchmark (device-time only; falls back to CUDA events).
# --------------------------------------------------------------------------- #
def _measure_cuda_event(fn, repetition):
    import torch

    times_ms = []
    for _ in range(max(1, int(repetition))):
        torch.cuda.synchronize()
        s = torch.cuda.Event(enable_timing=True)
        e = torch.cuda.Event(enable_timing=True)
        s.record()
        fn()
        e.record()
        torch.cuda.synchronize()
        times_ms.append(s.elapsed_time(e))
    return times_ms


class _TimedRun:
    def __init__(self):
        self._rerun = None
        self.outputs = None

    def _bind(self, rerun, outputs=None):
        self._rerun = rerun
        self.outputs = outputs

    @property
    def bound(self):
        return self._rerun is not None

    def rerun(self):
        if self._rerun is None:
            raise RuntimeError("timed run was never bound")
        self.outputs = self._rerun()
        return self.outputs


def _benchmark_cuda_graph(
    fn,
    warmup=10,
    repetition=100,
    target_ms=1.0,
    max_graph_repeats=200,
    timed_run=None,
):
    import torch

    for _ in range(max(0, int(warmup))):
        fn()
    torch.cuda.synchronize()

    meta = {"benchmark_target_ms": float(target_ms), "benchmark_samples": int(repetition)}
    try:
        stream = torch.cuda.Stream()
        stream.wait_stream(torch.cuda.current_stream())
        with torch.cuda.stream(stream):
            est = torch.cuda.CUDAGraph()
            with torch.cuda.graph(est):
                for _ in range(3):
                    fn()
            torch.cuda.synchronize()
            s, e = torch.cuda.Event(enable_timing=True), torch.cuda.Event(enable_timing=True)
            s.record(stream)
            est.replay()
            e.record(stream)
            torch.cuda.synchronize()
            est_ms = s.elapsed_time(e) / 3
            repeats = min(max_graph_repeats, max(1, int(target_ms / max(est_ms, 1e-9))))

            graph = torch.cuda.CUDAGraph()
            with torch.cuda.graph(graph):
                captured_outputs = None
                for _ in range(repeats):
                    captured_outputs = fn()
            torch.cuda.synchronize()

            times = []
            for _ in range(max(1, int(repetition))):
                s, e = torch.cuda.Event(enable_timing=True), torch.cuda.Event(enable_timing=True)
                s.record(stream)
                graph.replay()
                e.record(stream)
                torch.cuda.synchronize()
                times.append(s.elapsed_time(e) / repeats)
        mean_ms = sum(times) / len(times)
        if mean_ms < 1e-5:
            raise RuntimeError("empty_cuda_graph_capture")
        meta.update(benchmark_method="cuda_graph", benchmark_effective_repeats=int(repeats))
        if timed_run is not None:
            def _replay_once():
                stream.wait_stream(torch.cuda.current_stream())
                with torch.cuda.stream(stream):
                    graph.replay()
                torch.cuda.synchronize()
                return captured_outputs

            timed_run._bind(_replay_once, captured_outputs)
        return mean_ms, meta
    except Exception as exc:
        try:
            torch.cuda.synchronize()
        except Exception:
            pass
        if timed_run is not None:
            raise RuntimeError(
                "CUDA-graph capture failed; timed outputs cannot be validated "
                "through a separate event-timed invocation"
            ) from exc
        times = _measure_cuda_event(fn, repetition)
        meta.update(
            benchmark_method="cuda_event_fallback",
            benchmark_effective_repeats=int(repetition),
            benchmark_fallback_reason=f"{type(exc).__name__}: {str(exc)[:160]}",
        )
        return sum(times) / len(times), meta


# --------------------------------------------------------------------------- #
# Build the two grouped-GEMM invocations of one MoE forward (untimed setup).
# --------------------------------------------------------------------------- #
def _make(case: dict) -> dict:
    """Build a case at its scored shape.

    There is deliberately no correctness/performance switch here: a shape that is
    timed must also be the shape that is validated, or the scored code path can
    differ from the checked one.
    """
    torch = _torch()
    from sglang.jit_kernel.minimax_m3 import swiglu_oai_split
    from sglang.srt.layers.moe.moe_runner.triton_utils.mxfp8_moe_amd_gfx95 import _grouped_gemm_mxfp8
    from sglang.srt.layers.quantization.mxfp8_amd_gfx95 import (
        _mxfp8_e4m3_quantize_torch,
        mxfp8_e4m3_quantize,
    )
    from sglang.srt.layers.moe.moe_runner.triton_utils.moe_align_block_size import (
        moe_align_block_size,
    )

    p = case["params"]
    T = p["tokens"]
    H, I, E, top_k = p["hidden"], p["inter"], p["experts"], p["top_k"]
    alpha, beta, limit = p["alpha"], p["beta"], p["limit"]
    torch.manual_seed(case.get("seed", 0))

    hidden = torch.randn(T, H, device="cuda", dtype=torch.bfloat16) * 0.5
    w13_bf16 = torch.randn(E, 2 * I, H, device="cuda", dtype=torch.bfloat16) * 0.1
    w2_bf16 = torch.randn(E, H, I, device="cuda", dtype=torch.bfloat16) * 0.1
    w13_fp8, w13_scale = _mxfp8_e4m3_quantize_torch(w13_bf16)
    w2_fp8, w2_scale = _mxfp8_e4m3_quantize_torch(w2_bf16)

    logits = torch.randn(T, E, device="cuda", dtype=torch.float32)
    topk_weights, topk_ids = logits.softmax(dim=-1).topk(top_k, dim=-1)
    topk_weights = topk_weights.to(torch.float32)
    topk_ids = topk_ids.to(torch.int32)

    M = T * top_k
    sorted_ids, expert_ids, num_post = moe_align_block_size(topk_ids, BLOCK_M, E)
    a_q, a_s = mxfp8_e4m3_quantize(hidden)

    # GEMM1 (materialize the real intermediate so GEMM2 inputs are realistic).
    g1 = _grouped_gemm_mxfp8(
        a_q, a_s, w13_fp8, w13_scale, sorted_ids, expert_ids, num_post,
        M, top_k, BLOCK_M, hidden.dtype, a_div=top_k,
    )
    act = swiglu_oai_split(g1, alpha=alpha, beta=beta, limit=limit, out_dtype=hidden.dtype)
    act_q, act_s = mxfp8_e4m3_quantize(act)
    mul_weight = topk_weights.reshape(-1).to(torch.float32)

    gemm1_args = dict(
        a_q=a_q, a_scale=a_s, w=w13_fp8, w_scale=w13_scale, sorted_token_ids=sorted_ids,
        expert_ids=expert_ids, num_tokens_post_padded=num_post, num_valid_tokens=M,
        top_k=top_k, block_m=BLOCK_M, out_dtype=hidden.dtype, a_div=top_k,
    )
    gemm2_args = dict(
        a_q=act_q, a_scale=act_s, w=w2_fp8, w_scale=w2_scale, sorted_token_ids=sorted_ids,
        expert_ids=expert_ids, num_tokens_post_padded=num_post, num_valid_tokens=M,
        top_k=top_k, block_m=BLOCK_M, out_dtype=torch.float32, a_div=1, mul_weight_by=mul_weight,
    )
    return {
        "cfg": case, "T": T, "H": H, "I": I, "top_k": top_k,
        "alpha": alpha, "beta": beta, "limit": limit,
        "gemm1_args": gemm1_args, "gemm2_args": gemm2_args,
        "topk_weights": topk_weights, "topk_ids": topk_ids,
        "a_q": a_q, "a_s": a_s, "w13_fp8": w13_fp8, "w13_scale": w13_scale,
        "w2_fp8": w2_fp8, "w2_scale": w2_scale,
    }


def _run_gemms(inputs: dict):
    """The timed region: the two grouped-GEMM launches of one MoE forward."""
    from sglang.srt.layers.moe.moe_runner.triton_utils.mxfp8_moe_amd_gfx95 import _grouped_gemm_mxfp8

    gemm1 = _grouped_gemm_mxfp8(**inputs["gemm1_args"])
    gemm2 = _grouped_gemm_mxfp8(**inputs["gemm2_args"])
    return gemm1, gemm2


def _fused_output(inputs: dict):
    """Full MoE output reconstructed from the two grouped GEMMs (for correctness)."""
    torch = _torch()
    from sglang.jit_kernel.minimax_m3 import swiglu_oai_split
    from sglang.srt.layers.moe.moe_runner.triton_utils.mxfp8_moe_amd_gfx95 import _grouped_gemm_mxfp8
    from sglang.srt.layers.quantization.mxfp8_amd_gfx95 import mxfp8_e4m3_quantize

    g1 = _grouped_gemm_mxfp8(**inputs["gemm1_args"])
    act = swiglu_oai_split(
        g1, alpha=inputs["alpha"], beta=inputs["beta"], limit=inputs["limit"],
        out_dtype=torch.bfloat16,
    )
    act_q, act_s = mxfp8_e4m3_quantize(act)
    args = dict(inputs["gemm2_args"])
    args["a_q"], args["a_scale"] = act_q, act_s
    g2 = _grouped_gemm_mxfp8(**args)  # [M, H] fp32, top-k weighted
    T, top_k, H = inputs["T"], inputs["top_k"], inputs["H"]
    return g2.view(T, top_k, H).sum(dim=1).to(torch.bfloat16)


def _timed_references(inputs: dict):
    """Independent references for the two outputs produced inside the timed region."""
    torch = _torch()
    from sglang.srt.layers.quantization.mxfp8_amd_gfx95 import dequant_mxfp8_to_bf16

    x = dequant_mxfp8_to_bf16(inputs["a_q"], inputs["a_s"]).float()
    act = dequant_mxfp8_to_bf16(
        inputs["gemm2_args"]["a_q"],
        inputs["gemm2_args"]["a_scale"],
    ).float()
    w13 = dequant_mxfp8_to_bf16(inputs["w13_fp8"], inputs["w13_scale"])
    w2 = dequant_mxfp8_to_bf16(inputs["w2_fp8"], inputs["w2_scale"])

    topk_ids = inputs["topk_ids"].long().reshape(-1)
    topk_weights = inputs["topk_weights"].float().reshape(-1)
    top_k = inputs["top_k"]
    flat_token = torch.arange(
        inputs["T"], device=x.device
    ).unsqueeze(1).expand(inputs["T"], top_k).reshape(-1)

    gemm1 = torch.empty(
        topk_ids.numel(),
        2 * inputs["I"],
        device=x.device,
        dtype=torch.bfloat16,
    )
    gemm2 = torch.empty(
        topk_ids.numel(),
        inputs["H"],
        device=x.device,
        dtype=torch.float32,
    )
    for expert in range(w13.shape[0]):
        slots = torch.where(topk_ids == expert)[0]
        if slots.numel() == 0:
            continue
        rows = flat_token[slots]
        gemm1[slots] = (x[rows] @ w13[expert].float().T).to(torch.bfloat16)
        gemm2[slots] = (
            act[slots] @ w2[expert].float().T
        ) * topk_weights[slots].unsqueeze(-1)
    return gemm1, gemm2


def _assert_timed_outputs(inputs: dict, timed: _TimedRun) -> None:
    if not timed.bound or not isinstance(timed.outputs, tuple) or len(timed.outputs) != 2:
        raise RuntimeError("benchmark did not expose both timed GEMM outputs")

    for output in timed.outputs:
        output.fill_(float("nan"))
    got1, got2 = timed.rerun()
    ref1, ref2 = _timed_references(inputs)
    tol = inputs["cfg"]["params"].get("max_relerr", 0.08)
    err1 = _relerr(got1, ref1)
    err2 = _relerr(got2, ref2)
    assert err1 < tol, (inputs["cfg"]["id"], "timed_gemm1", err1, tol)
    assert err2 < tol, (inputs["cfg"]["id"], "timed_gemm2", err2, tol)


def _reference(inputs: dict):
    """Dequantized torch reference for one MoE forward.

    Iterates experts rather than (token, slot) pairs: every token routed to an
    expert is one batched matmul instead of a Python step. The loop this replaces
    ran T*top_k times and synchronised on ``topk_ids`` each step, which is what
    made a full-shape correctness run impractical.

    The dequantized weights stay bf16 and are cast per expert, so the reference
    never materialises an fp32 copy of the whole expert bank.
    """
    torch = _torch()
    from sglang.srt.layers.quantization.mxfp8_amd_gfx95 import dequant_mxfp8_to_bf16

    x = dequant_mxfp8_to_bf16(inputs["a_q"], inputs["a_s"]).float()
    w13 = dequant_mxfp8_to_bf16(inputs["w13_fp8"], inputs["w13_scale"])
    w2 = dequant_mxfp8_to_bf16(inputs["w2_fp8"], inputs["w2_scale"])
    T, I, top_k = inputs["T"], inputs["I"], inputs["top_k"]
    alpha, beta, limit = inputs["alpha"], inputs["beta"], inputs["limit"]
    topk_weights, topk_ids = inputs["topk_weights"], inputs["topk_ids"]
    H = inputs["H"]
    num_experts = w13.shape[0]

    out = torch.zeros(T, H, device=x.device, dtype=torch.float32)
    flat_expert = topk_ids.long().reshape(-1)
    flat_token = torch.arange(
        T, device=x.device
    ).unsqueeze(1).expand(T, top_k).reshape(-1)
    flat_weight = topk_weights.float().reshape(-1)

    # moe_align_block_size can emit padding slots outside the expert range.
    keep = (flat_expert >= 0) & (flat_expert < num_experts)
    flat_expert = flat_expert[keep]
    flat_token = flat_token[keep]
    flat_weight = flat_weight[keep]

    order = torch.argsort(flat_expert)
    counts = torch.bincount(flat_expert[order], minlength=num_experts)
    offsets = torch.cumsum(counts, dim=0).tolist()
    start = 0
    for expert, stop in enumerate(offsets):
        if stop == start:
            continue
        rows = flat_token[order[start:stop]]
        g1 = x[rows] @ w13[expert].float().T  # [n, 2*I]
        gate = g1[:, :I].clamp(max=limit)
        up = g1[:, I:].clamp(min=-limit, max=limit)
        act = gate * torch.sigmoid(alpha * gate) * (up + beta)
        contrib = (act @ w2[expert].float().T) * flat_weight[
            order[start:stop]
        ].unsqueeze(-1)
        out.index_add_(0, rows, contrib)
        start = stop
    return out.to(torch.bfloat16)


# --------------------------------------------------------------------------- #
# Modes
# --------------------------------------------------------------------------- #
def _compile_smoke_case(case: dict) -> dict:
    """Shrink a case so the compile smoke test stays cheap.

    Only ``compile`` may use this. Correctness and performance must share one
    shape, otherwise the scored path is not the validated path.
    """
    params = dict(case["params"])
    params["tokens"] = min(params["tokens"], COMPILE_SMOKE_MAX_TOKENS)
    return {**case, "params": params}


def run_compile() -> None:
    inputs = _make(_compile_smoke_case(CASES[0]))
    _run_gemms(inputs)
    _torch().cuda.synchronize()
    print("mxfp8_grouped_gemm compile smoke: PASS")


def run_correctness() -> None:
    torch = _torch()
    for case in CASES:
        inputs = _make(case)
        got = _fused_output(inputs)
        torch.cuda.synchronize()
        err = _relerr(got, _reference(inputs))
        tol = case["params"].get("max_relerr", 0.08)
        assert err < tol, (case["id"], err, tol)
        print("correctness PASS", case["id"], f"T={inputs['T']}", f"relerr={err:.4f}")


def run_performance() -> None:
    torch = _torch()
    rows = []
    for case in CASES:
        inputs = _make(case)
        _run_gemms(inputs)
        torch.cuda.synchronize()
        timed = _TimedRun()
        ms, bmeta = _benchmark_cuda_graph(
            lambda: _run_gemms(inputs),
            timed_run=timed,
        )
        _assert_timed_outputs(inputs, timed)
        row = {
            "test_case_id": case["id"],
            "execution_time_ms": ms,
            "metadata": {**case["params"], "regime": case.get("regime"), **bmeta},
        }
        rows.append(row)
        print(case["id"], f"{ms:.6f} ms", bmeta.get("benchmark_method"),
              bmeta.get("benchmark_fallback_reason", ""))
    out = WORKSPACE / "build"
    out.mkdir(parents=True, exist_ok=True)
    (out / "performance_report.json").write_text(json.dumps(rows, indent=2))


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("mode", choices=["compile", "correctness", "performance", "manifest"])
    mode = parser.parse_args().mode
    if mode == "manifest":
        print(json.dumps(SPEC, indent=2))
        return
    _configure()
    {"compile": run_compile, "correctness": run_correctness, "performance": run_performance}[mode]()


import argparse
import importlib.util
import sys
from pathlib import Path



def _import_task_runner():
    """This merged file inlines task_runner above; return this module."""
    return sys.modules[__name__]

def _case_map(tr):
    return {c["id"]: c for c in tr.CASES}


def _run_correctness(tr, mode: str) -> int:
    """Rebuild-free correctness: reuse the harness's fused output vs reference."""
    torch = tr._torch()
    all_ok = True
    for case in tr.CASES:
        inputs = tr._make(case)
        got = tr._fused_output(inputs)
        torch.cuda.synchronize()
        err = tr._relerr(got, tr._reference(inputs))
        tol = case["params"].get("max_relerr", 0.08)
        ok = err < tol
        all_ok = all_ok and ok
        # Informational only. Intentionally NOT the "SNR:" token (see module doc).
        print(f"# case {case['id']}: relerr={err:.4f} tol={tol} ok={ok}")
    print(f"allclose: {all_ok}")
    return 0


def _run_bench(tr, warmup: int, iters: int) -> int:
    """Graph-timed bench: one CUDA-graph mean per case (reuses task_runner)."""
    torch = tr._torch()
    means = []
    for case in tr.CASES:
        inputs = tr._make(case)
        tr._run_gemms(inputs)  # warm/JIT settle before capture
        torch.cuda.synchronize()
        timed = tr._TimedRun()
        ms, meta = tr._benchmark_cuda_graph(
            lambda i=inputs: tr._run_gemms(i),
            warmup=max(1, warmup),
            repetition=max(1, iters),
            timed_run=timed,
        )
        tr._assert_timed_outputs(inputs, timed)
        means.append(ms)
        # Per-case time (forge can round-trip the case_id to --profile-case).
        print(f"case_ms: {case['id']} {ms:.6f}")
        print(f"# bench {case['id']}: {ms:.6f} ms method={meta.get('benchmark_method')}"
              f" {meta.get('benchmark_fallback_reason', '')}".rstrip())
    # Aggregate forge uses for keep/revert = arithmetic mean across cases
    # (matches arena_task_adapter / Arena's evaluator). Label it honestly.
    agg = sum(means) / len(means)
    print(f"mean_ms: {agg:.6f}")
    return 0


def _run_profile(tr, case_id: str) -> int:
    """Kernel-only profiling for one case: warm, a few launches, sync, exit 0."""
    torch = tr._torch()
    cases = _case_map(tr)
    if case_id and case_id in cases:
        case = cases[case_id]
    else:
        # Default: the largest / dominant case (most tokens) when unspecified.
        case = max(tr.CASES, key=lambda c: int(c["params"]["tokens"]))
    inputs = tr._make(case)
    for _ in range(5):          # settle Triton JIT / autotune selection
        tr._run_gemms(inputs)
    torch.cuda.synchronize()
    for _ in range(3):          # profiled launches (profiler replays per group)
        tr._run_gemms(inputs)
    torch.cuda.synchronize()
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="SGLang MXFP8 grouped-GEMM forge driver")
    parser.add_argument("--shape", default="default")  # task owns its shapes
    parser.add_argument("--mode", default="full")       # all modes -> task correctness
    parser.add_argument("--bench-mode", action="store_true")
    parser.add_argument("--profile-run", action="store_true")
    parser.add_argument("--profile-case", default="")
    parser.add_argument("--warmup", type=int, default=10)
    parser.add_argument("--iters", type=int, default=30)
    args, _unknown = parser.parse_known_args()

    tr = _import_task_runner()
    tr._configure()  # set gfx950 arch env + make the seeded sglang copy importable

    import torch
    if not torch.cuda.is_available():
        print("error: ROCm GPU (gfx950) is required (torch.cuda.is_available() is False)",
              file=sys.stderr)
        return 1

    if args.profile_run:
        return _run_profile(tr, args.profile_case)
    if args.bench_mode:
        return _run_bench(tr, args.warmup, args.iters)
    return _run_correctness(tr, args.mode)


if __name__ == "__main__":
    sys.exit(main())
