/-
Copyright (c) 2026 Ranvier Systems. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Pehle
-/
import LeanTest
import Cuda

/-!
# Qwen3.6 device-primitive gates vs NumPy fixtures

Drives every kernel of `LeanCudaQwen.Qwen36.Primitives` against the checked-in fixtures of
`fixtures/` (generated by `gen_fixtures.py`, tiny configuration: hidden 256, head 64, rotary 16,
seq 8). FP32 gates require max abs err ≤ 1e-5; BF16-storage gates require relative L2 ≤ 2e-2
against the same FP32 oracle; gathers and casts are bit-exact. The conv decode step is
additionally cross-checked against the final row of the full-sequence gate.

Invocation: `cuda_qwen36_primitives_test <fixtures-dir>`.
-/

namespace Qwen36PrimitivesGate

open Cuda.Qwen36.Primitives

private def rows : Nat := 8
private def hidden : Nat := 256
private def headDim : Nat := 64
private def heads : Nat := 4
private def rotaryHalf : Nat := 8
private def rotaryDim : Nat := 16
private def seqLen : Nat := 8
private def vocab : Nat := 512

private def rows32 : UInt32 := 8
private def hidden32 : UInt32 := 256
private def headDim32 : UInt32 := 64
private def heads32 : UInt32 := 4
private def seqLen32 : UInt32 := 8
private def eps : Float32 := 1e-6
private def theta : Float32 := 1e7
private def ropePosition : Float32 := 5

private def pushUInt16 (bytes : ByteArray) (value : UInt16) : ByteArray :=
  (bytes.push value.toUInt8).push (value >>> 8).toUInt8

private def pushUInt32 (bytes : ByteArray) (value : UInt32) : ByteArray :=
  (((bytes.push value.toUInt8).push (value >>> 8).toUInt8).push
    (value >>> 16).toUInt8).push (value >>> 24).toUInt8

private def readUInt16 (bytes : ByteArray) (index : Nat) : UInt16 :=
  let offset := index * 2
  bytes[offset]!.toUInt16 ||| (bytes[offset + 1]!.toUInt16 <<< 8)

private def readFloat32 (bytes : ByteArray) (index : Nat) : Float32 :=
  let offset := index * 4
  Float32.ofBits <| bytes[offset]!.toUInt32 |||
    (bytes[offset + 1]!.toUInt32 <<< 8) |||
    (bytes[offset + 2]!.toUInt32 <<< 16) ||| (bytes[offset + 3]!.toUInt32 <<< 24)

private def loadFixture (dir : String) (name : String) (count : Nat) : IO ByteArray := do
  let bytes ← IO.FS.readBinFile (dir ++ "/" ++ name ++ ".f32.bin")
  unless bytes.size == count * 4 do
    throw <| IO.userError s!"fixture {name}: expected {count * 4} bytes, found {bytes.size}"
  return bytes

private def allocF32 (count : Nat) : IO (Cuda.Buffer Float32) :=
  Cuda.Buffer.alloc Float32 count.toUSize

private def allocBF16 (count : Nat) : IO (Cuda.Buffer Cuda.BFloat16) :=
  Cuda.Buffer.alloc Cuda.BFloat16 count.toUSize

private def uploadF32 (dir : String) (name : String) (count : Nat) (stream : Cuda.Stream) :
    IO (Cuda.Buffer Float32) := do
  let bytes ← loadFixture dir name count
  let buffer ← allocF32 count
  buffer.copyFrom bytes stream
  return buffer

private def uploadBF16 (dir : String) (name : String) (count : Nat) (stream : Cuda.Stream) :
    IO (Cuda.Buffer Cuda.BFloat16) := do
  let bytes ← loadFixture dir name count
  let mut packed := ByteArray.emptyWithCapacity (count * 2)
  for i in [:count] do
    packed := pushUInt16 packed (Cuda.BFloat16.ofFloat32 (readFloat32 bytes i)).bits
  let buffer ← allocBF16 count
  buffer.copyFrom packed stream
  return buffer

private def uploadIds (dir : String) (name : String) (count : Nat) (stream : Cuda.Stream) :
    IO (Cuda.Buffer UInt32) := do
  let bytes ← loadFixture dir name count
  let mut packed := ByteArray.emptyWithCapacity (count * 4)
  for i in [:count] do
    packed := pushUInt32 packed (readFloat32 bytes i).toUInt32
  let buffer ← Cuda.Buffer.alloc UInt32 count.toUSize
  buffer.copyFrom packed stream
  return buffer

/-- Max-abs-err comparison for FP32 tensors against the oracle. -/
private def checkF32 (label : String) (actual expected : ByteArray) (count : Nat)
    (tol : Float32) : IO Unit := do
  let mut worst : Float32 := 0
  let mut worstAt : Nat := 0
  for i in [:count] do
    let err := Float32.abs (readFloat32 actual i - readFloat32 expected i)
    if err > worst then
      worst := err
      worstAt := i
  unless worst ≤ tol do
    LeanTest.fail (s!"{label}: max abs err {worst} at {worstAt} exceeds {tol} " ++
      s!"(actual {readFloat32 actual worstAt}, expected {readFloat32 expected worstAt})")

/-- Relative-L2 comparison for FP32 tensors (used for row scalars of BF16 runs). -/
private def checkRelL2F32 (label : String) (actual expected : ByteArray) (count : Nat)
    (tol : Float32) : IO Unit := do
  let mut num : Float32 := 0
  let mut den : Float32 := 0
  for i in [:count] do
    let d := readFloat32 actual i - readFloat32 expected i
    let e := readFloat32 expected i
    num := num + d * d
    den := den + e * e
  let rel := Float32.sqrt (num / den)
  unless rel ≤ tol do
    LeanTest.fail s!"{label}: rel L2 {rel} exceeds {tol}"

/-- Relative-L2 comparison for BF16 tensors against the FP32 oracle. -/
private def checkRelL2BF16 (label : String) (actual expected : ByteArray) (count : Nat)
    (tol : Float32) : IO Unit := do
  let mut num : Float32 := 0
  let mut den : Float32 := 0
  for i in [:count] do
    let a := (BFloat16.ofBits (readUInt16 actual i)).toFloat32
    let e := readFloat32 expected i
    num := num + (a - e) * (a - e)
    den := den + e * e
  let rel := Float32.sqrt (num / den)
  unless rel ≤ tol do
    LeanTest.fail s!"{label}: rel L2 {rel} exceeds {tol}"

/-- Bit-exact comparison for FP32 tensors (copies and exact widenings). -/
private def checkExactF32 (label : String) (actual expected : ByteArray) (count : Nat) :
    IO Unit := do
  for i in [:count] do
    unless (readFloat32 actual i).toBits == (readFloat32 expected i).toBits do
      LeanTest.fail (s!"{label}: mismatch at {i} " ++
        s!"(actual {readFloat32 actual i}, expected {readFloat32 expected i})")

/-- Exact comparison for BF16 tensors via their FP32 images. -/
private def checkExactBF16 (label : String) (actual expected : ByteArray) (count : Nat) :
    IO Unit := do
  for i in [:count] do
    let a := (BFloat16.ofBits (readUInt16 actual i)).toFloat32
    unless a.toBits == (readFloat32 expected i).toBits do
      LeanTest.fail (s!"{label}: mismatch at {i} " ++
        s!"(actual {a}, expected {readFloat32 expected i})")

private def gateRmsNormF32 (dir : String) (stream : Cuda.Stream) : IO Unit := do
  let x ← uploadF32 dir "rms_x.8x256" (rows * hidden) stream
  let weight ← uploadF32 dir "rms_w.256" hidden stream
  let dy ← uploadF32 dir "rms_dy.8x256" (rows * hidden) stream
  let output ← allocF32 (rows * hidden)
  let inverseRms ← allocF32 rows
  let handle ← rmsNormForwardF32 stream x weight output inverseRms rows32 hidden32 eps
  handle.waitChecked "rmsnorm-fwd-f32"
  checkF32 "rmsnorm-fwd-f32 y" (← output.copyTo stream)
    (← loadFixture dir "rms_y.8x256" (rows * hidden)) (rows * hidden) 1e-5
  checkF32 "rmsnorm-fwd-f32 inv" (← inverseRms.copyTo stream)
    (← loadFixture dir "rms_inv.8" rows) rows 1e-5
  let dx ← allocF32 (rows * hidden)
  let dw ← allocF32 hidden
  let backInput ← rmsNormBackwardInputF32 stream x weight dy dx inverseRms rows32
    hidden32
  backInput.waitChecked "rmsnorm-bwd-input-f32"
  let backWeight ← rmsNormBackwardWeightF32 stream x dy inverseRms dw rows32 hidden32
  backWeight.waitChecked "rmsnorm-bwd-weight-f32"
  checkF32 "rmsnorm-bwd-f32 dx" (← dx.copyTo stream)
    (← loadFixture dir "rms_dx.8x256" (rows * hidden)) (rows * hidden) 1e-5
  checkF32 "rmsnorm-bwd-f32 dw" (← dw.copyTo stream)
    (← loadFixture dir "rms_dw.256" hidden) hidden 1e-5

private def gateRmsNormBF16 (dir : String) (stream : Cuda.Stream) : IO Unit := do
  let x ← uploadBF16 dir "rms_x.8x256" (rows * hidden) stream
  let weight ← uploadBF16 dir "rms_w.256" hidden stream
  let dy ← uploadBF16 dir "rms_dy.8x256" (rows * hidden) stream
  let output ← allocBF16 (rows * hidden)
  let inverseRms ← allocF32 rows
  let handle ← rmsNormForwardBF16 stream x weight output inverseRms rows32 hidden32
    eps
  handle.waitChecked "rmsnorm-fwd-bf16"
  checkRelL2BF16 "rmsnorm-fwd-bf16 y" (← output.copyTo stream)
    (← loadFixture dir "rms_y.8x256" (rows * hidden)) (rows * hidden) 2e-2
  checkRelL2F32 "rmsnorm-fwd-bf16 inv" (← inverseRms.copyTo stream)
    (← loadFixture dir "rms_inv.8" rows) rows 2e-2
  let dx ← allocBF16 (rows * hidden)
  let dw ← allocBF16 hidden
  let backInput ← rmsNormBackwardInputBF16 stream x weight dy dx inverseRms rows32
    hidden32
  backInput.waitChecked "rmsnorm-bwd-input-bf16"
  let backWeight ← rmsNormBackwardWeightBF16 stream x dy inverseRms dw rows32 hidden32
  backWeight.waitChecked "rmsnorm-bwd-weight-bf16"
  checkRelL2BF16 "rmsnorm-bwd-bf16 dx" (← dx.copyTo stream)
    (← loadFixture dir "rms_dx.8x256" (rows * hidden)) (rows * hidden) 2e-2
  checkRelL2BF16 "rmsnorm-bwd-bf16 dw" (← dw.copyTo stream)
    (← loadFixture dir "rms_dw.256" hidden) hidden 2e-2

private def gateGatedRmsNormF32 (dir : String) (stream : Cuda.Stream) : IO Unit := do
  let x ← uploadF32 dir "gated_x.8x64" (rows * headDim) stream
  let z ← uploadF32 dir "gated_z.8x64" (rows * headDim) stream
  let dy ← uploadF32 dir "gated_dy.8x64" (rows * headDim) stream
  let output ← allocF32 (rows * headDim)
  let inverseRms ← allocF32 rows
  let handle ← gatedRmsNormForwardF32 stream x z output inverseRms rows32 headDim32
    eps
  handle.waitChecked "gated-rmsnorm-fwd-f32"
  checkF32 "gated-rmsnorm-fwd-f32 y" (← output.copyTo stream)
    (← loadFixture dir "gated_y.8x64" (rows * headDim)) (rows * headDim) 1e-5
  checkF32 "gated-rmsnorm-fwd-f32 inv" (← inverseRms.copyTo stream)
    (← loadFixture dir "gated_inv.8" rows) rows 1e-5
  let dx ← allocF32 (rows * headDim)
  let dz ← allocF32 (rows * headDim)
  let backward ← gatedRmsNormBackwardF32 stream x z dy dx dz inverseRms rows32
    headDim32
  backward.waitChecked "gated-rmsnorm-bwd-f32"
  checkF32 "gated-rmsnorm-bwd-f32 dx" (← dx.copyTo stream)
    (← loadFixture dir "gated_dx.8x64" (rows * headDim)) (rows * headDim) 1e-5
  checkF32 "gated-rmsnorm-bwd-f32 dz" (← dz.copyTo stream)
    (← loadFixture dir "gated_dz.8x64" (rows * headDim)) (rows * headDim) 1e-5

private def gateGatedRmsNormBF16 (dir : String) (stream : Cuda.Stream) : IO Unit := do
  let x ← uploadBF16 dir "gated_x.8x64" (rows * headDim) stream
  let z ← uploadBF16 dir "gated_z.8x64" (rows * headDim) stream
  let dy ← uploadBF16 dir "gated_dy.8x64" (rows * headDim) stream
  let output ← allocBF16 (rows * headDim)
  let inverseRms ← allocF32 rows
  let handle ← gatedRmsNormForwardBF16 stream x z output inverseRms rows32 headDim32
    eps
  handle.waitChecked "gated-rmsnorm-fwd-bf16"
  checkRelL2BF16 "gated-rmsnorm-fwd-bf16 y" (← output.copyTo stream)
    (← loadFixture dir "gated_y.8x64" (rows * headDim)) (rows * headDim) 2e-2
  let dx ← allocBF16 (rows * headDim)
  let dz ← allocBF16 (rows * headDim)
  let backward ← gatedRmsNormBackwardBF16 stream x z dy dx dz inverseRms rows32
    headDim32
  backward.waitChecked "gated-rmsnorm-bwd-bf16"
  checkRelL2BF16 "gated-rmsnorm-bwd-bf16 dx" (← dx.copyTo stream)
    (← loadFixture dir "gated_dx.8x64" (rows * headDim)) (rows * headDim) 2e-2
  checkRelL2BF16 "gated-rmsnorm-bwd-bf16 dz" (← dz.copyTo stream)
    (← loadFixture dir "gated_dz.8x64" (rows * headDim)) (rows * headDim) 2e-2

private def gateRope (dir : String) (stream : Cuda.Stream) : IO Unit := do
  let invFreq ← allocF32 rotaryHalf
  let table ← ropeInvFreq stream invFreq rotaryHalf.toUInt32 rotaryDim.toUInt32 theta
  table.waitChecked "rope-invfreq"
  checkF32 "rope-invfreq" (← invFreq.copyTo stream)
    (← loadFixture dir "rope_invfreq.8" rotaryHalf) rotaryHalf 1e-5
  let q ← uploadF32 dir "rope_q.4x64" (heads * headDim) stream
  let k ← uploadF32 dir "rope_k.4x64" (heads * headDim) stream
  let qOut ← allocF32 (heads * headDim)
  let kOut ← allocF32 (heads * headDim)
  let forward ← ropeApplyForwardF32 stream q k invFreq qOut kOut heads32 headDim32
    rotaryHalf.toUInt32 ropePosition
  forward.waitChecked "rope-apply-fwd-f32"
  checkF32 "rope-apply-fwd-f32 q" (← qOut.copyTo stream)
    (← loadFixture dir "rope_q_out.4x64" (heads * headDim)) (heads * headDim) 1e-5
  checkF32 "rope-apply-fwd-f32 k" (← kOut.copyTo stream)
    (← loadFixture dir "rope_k_out.4x64" (heads * headDim)) (heads * headDim) 1e-5
  let dq ← uploadF32 dir "rope_dq.4x64" (heads * headDim) stream
  let dk ← uploadF32 dir "rope_dk.4x64" (heads * headDim) stream
  let dqPre ← allocF32 (heads * headDim)
  let dkPre ← allocF32 (heads * headDim)
  let backward ← ropeApplyBackwardF32 stream dq dk invFreq dqPre dkPre heads32
    headDim32 rotaryHalf.toUInt32 ropePosition
  backward.waitChecked "rope-apply-bwd-f32"
  checkF32 "rope-apply-bwd-f32 dq" (← dqPre.copyTo stream)
    (← loadFixture dir "rope_dq_pre.4x64" (heads * headDim)) (heads * headDim) 1e-5
  checkF32 "rope-apply-bwd-f32 dk" (← dkPre.copyTo stream)
    (← loadFixture dir "rope_dk_pre.4x64" (heads * headDim)) (heads * headDim) 1e-5

private def gateConv (dir : String) (stream : Cuda.Stream) : IO Unit := do
  let x ← uploadF32 dir "conv_x.8x256" (seqLen * hidden) stream
  let weight ← uploadF32 dir "conv_w.256x4" (hidden * 4) stream
  let dy ← uploadF32 dir "conv_dy.8x256" (seqLen * hidden) stream
  let output ← allocF32 (seqLen * hidden)
  let forward ← conv1dSiLUForwardF32 stream x weight output seqLen32 hidden32
  forward.waitChecked "conv-fwd-f32"
  checkF32 "conv-fwd-f32 y" (← output.copyTo stream)
    (← loadFixture dir "conv_y.8x256" (seqLen * hidden)) (seqLen * hidden) 1e-5
  let dx ← allocF32 (seqLen * hidden)
  let dw ← allocF32 (hidden * 4)
  let backInput ← conv1dSiLUBackwardInputF32 stream x weight dy dx seqLen32 hidden32
  backInput.waitChecked "conv-bwd-input-f32"
  let backWeight ← conv1dSiLUBackwardWeightF32 stream x weight dy dw seqLen32 hidden32
  backWeight.waitChecked "conv-bwd-weight-f32"
  checkF32 "conv-bwd-f32 dx" (← dx.copyTo stream)
    (← loadFixture dir "conv_dx.8x256" (seqLen * hidden)) (seqLen * hidden) 1e-5
  checkF32 "conv-bwd-f32 dw" (← dw.copyTo stream)
    (← loadFixture dir "conv_dw.256x4" (hidden * 4)) (hidden * 4) 1e-5
  let state ← uploadF32 dir "conv_state.3x256" (3 * hidden) stream
  let xt ← uploadF32 dir "conv_xt.256" hidden stream
  let yt ← allocF32 hidden
  let stateOut ← allocF32 (3 * hidden)
  let decodeFwd ← conv1dSiLUDecodeForwardF32 stream state xt weight yt stateOut
    hidden32
  decodeFwd.waitChecked "conv-decode-fwd-f32"
  checkF32 "conv-decode-fwd-f32 yt" (← yt.copyTo stream)
    (← loadFixture dir "conv_yt.256" hidden) hidden 1e-5
  checkF32 "conv-decode-fwd-f32 state" (← stateOut.copyTo stream)
    (← loadFixture dir "conv_state_out.3x256" (3 * hidden)) (3 * hidden) 1e-5
  -- The decode step at t = seq - 1 must reproduce the final full-sequence row.
  let fullY ← loadFixture dir "conv_y.8x256" (seqLen * hidden)
  let mut tail := ByteArray.emptyWithCapacity (hidden * 4)
  for i in [:hidden] do
    tail := pushUInt32 tail (readFloat32 fullY ((seqLen - 1) * hidden + i)).toBits
  checkF32 "conv-decode-vs-full yt" (← yt.copyTo stream) tail hidden 1e-5
  let dyt ← uploadF32 dir "conv_dyt.256" hidden stream
  let dxt ← allocF32 hidden
  let dstate ← allocF32 (3 * hidden)
  let dwStep ← allocF32 (hidden * 4)
  let decodeBwd ← conv1dSiLUDecodeBackwardF32 stream state xt weight dyt dxt dstate
    dwStep hidden32
  decodeBwd.waitChecked "conv-decode-bwd-f32"
  checkF32 "conv-decode-bwd-f32 dxt" (← dxt.copyTo stream)
    (← loadFixture dir "conv_dxt.256" hidden) hidden 1e-5
  checkF32 "conv-decode-bwd-f32 dstate" (← dstate.copyTo stream)
    (← loadFixture dir "conv_dstate.3x256" (3 * hidden)) (3 * hidden) 1e-5
  checkF32 "conv-decode-bwd-f32 dw-step" (← dwStep.copyTo stream)
    (← loadFixture dir "conv_dw_step.256x4" (hidden * 4)) (hidden * 4) 1e-5

private def gateL2Norm (dir : String) (stream : Cuda.Stream) : IO Unit := do
  let x ← uploadF32 dir "l2_x.4x64" (heads * headDim) stream
  let dy ← uploadF32 dir "l2_dy.4x64" (heads * headDim) stream
  let output ← allocF32 (heads * headDim)
  let forward ← l2normForwardF32 stream x output heads32 headDim32 eps
  forward.waitChecked "l2norm-fwd-f32"
  checkF32 "l2norm-fwd-f32 y" (← output.copyTo stream)
    (← loadFixture dir "l2_y.4x64" (heads * headDim)) (heads * headDim) 1e-5
  let dx ← allocF32 (heads * headDim)
  let backward ← l2normBackwardF32 stream x dy dx heads32 headDim32 eps
  backward.waitChecked "l2norm-bwd-f32"
  checkF32 "l2norm-bwd-f32 dx" (← dx.copyTo stream)
    (← loadFixture dir "l2_dx.4x64" (heads * headDim)) (heads * headDim) 1e-5

private def gateSilu (dir : String) (stream : Cuda.Stream) : IO Unit := do
  let count := rows * hidden
  let x ← uploadF32 dir "silu_x.8x256" count stream
  let dy ← uploadF32 dir "silu_dy.8x256" count stream
  let y ← allocF32 count
  let forward ← siluForwardF32 stream x y count.toUInt32
  forward.waitChecked "silu-fwd-f32"
  checkF32 "silu-fwd-f32 y" (← y.copyTo stream)
    (← loadFixture dir "silu_y.8x256" count) count 1e-5
  let dx ← allocF32 count
  let backward ← siluBackwardF32 stream x dy dx count.toUInt32
  backward.waitChecked "silu-bwd-f32"
  checkF32 "silu-bwd-f32 dx" (← dx.copyTo stream)
    (← loadFixture dir "silu_dx.8x256" count) count 1e-5
  let xb ← uploadBF16 dir "silu_x.8x256" count stream
  let dyb ← uploadBF16 dir "silu_dy.8x256" count stream
  let yb ← allocBF16 count
  let forwardB ← siluForwardBF16 stream xb yb count.toUInt32
  forwardB.waitChecked "silu-fwd-bf16"
  checkRelL2BF16 "silu-fwd-bf16 y" (← yb.copyTo stream)
    (← loadFixture dir "silu_y.8x256" count) count 2e-2
  let dxb ← allocBF16 count
  let backwardB ← siluBackwardBF16 stream xb dyb dxb count.toUInt32
  backwardB.waitChecked "silu-bwd-bf16"
  checkRelL2BF16 "silu-bwd-bf16 dx" (← dxb.copyTo stream)
    (← loadFixture dir "silu_dx.8x256" count) count 2e-2

private def gateSwiglu (dir : String) (stream : Cuda.Stream) : IO Unit := do
  let count := rows * hidden
  let gate ← uploadF32 dir "swiglu_gate.8x256" count stream
  let up ← uploadF32 dir "swiglu_up.8x256" count stream
  let dh ← uploadF32 dir "swiglu_dh.8x256" count stream
  let hiddenOut ← allocF32 count
  let forward ← swigluForwardF32 stream gate up hiddenOut count.toUInt32
  forward.waitChecked "swiglu-fwd-f32"
  checkF32 "swiglu-fwd-f32 h" (← hiddenOut.copyTo stream)
    (← loadFixture dir "swiglu_h.8x256" count) count 1e-5
  let dgate ← allocF32 count
  let dup ← allocF32 count
  let backward ← swigluBackwardF32 stream gate up dh dgate dup count.toUInt32
  backward.waitChecked "swiglu-bwd-f32"
  checkF32 "swiglu-bwd-f32 dgate" (← dgate.copyTo stream)
    (← loadFixture dir "swiglu_dgate.8x256" count) count 1e-5
  checkF32 "swiglu-bwd-f32 dup" (← dup.copyTo stream)
    (← loadFixture dir "swiglu_dup.8x256" count) count 1e-5
  let gateB ← uploadBF16 dir "swiglu_gate.8x256" count stream
  let upB ← uploadBF16 dir "swiglu_up.8x256" count stream
  let dhB ← uploadBF16 dir "swiglu_dh.8x256" count stream
  let hiddenB ← allocBF16 count
  let forwardB ← swigluForwardBF16 stream gateB upB hiddenB count.toUInt32
  forwardB.waitChecked "swiglu-fwd-bf16"
  checkRelL2BF16 "swiglu-fwd-bf16 h" (← hiddenB.copyTo stream)
    (← loadFixture dir "swiglu_h.8x256" count) count 2e-2
  let dgateB ← allocBF16 count
  let dupB ← allocBF16 count
  let backwardB ← swigluBackwardBF16 stream gateB upB dhB dgateB dupB count.toUInt32
  backwardB.waitChecked "swiglu-bwd-bf16"
  checkRelL2BF16 "swiglu-bwd-bf16 dgate" (← dgateB.copyTo stream)
    (← loadFixture dir "swiglu_dgate.8x256" count) count 2e-2
  checkRelL2BF16 "swiglu-bwd-bf16 dup" (← dupB.copyTo stream)
    (← loadFixture dir "swiglu_dup.8x256" count) count 2e-2

private def gateEmbedding (dir : String) (stream : Cuda.Stream) : IO Unit := do
  let table ← uploadF32 dir "embed_table.512x256" (vocab * hidden) stream
  let ids ← uploadIds dir "embed_ids.8" rows stream
  let output ← allocF32 (rows * hidden)
  let gather ← embeddingGatherF32 stream table ids output rows32 hidden32
  gather.waitChecked "embed-gather-f32"
  checkExactF32 "embed-gather-f32" (← output.copyTo stream)
    (← loadFixture dir "embed_out.8x256" (rows * hidden)) (rows * hidden)
  let tableB ← uploadBF16 dir "embed_table.512x256" (vocab * hidden) stream
  let outputB ← allocBF16 (rows * hidden)
  let gatherB ← embeddingGatherBF16 stream tableB ids outputB rows32 hidden32
  gatherB.waitChecked "embed-gather-bf16"
  -- Exactness holds against the BF16-rounded oracle: gather copies survive the round trip.
  let expected ← loadFixture dir "embed_out.8x256" (rows * hidden)
  let mut rounded := ByteArray.emptyWithCapacity (rows * hidden * 4)
  for i in [:rows * hidden] do
    rounded := pushUInt32 rounded
      ((Cuda.BFloat16.ofFloat32 (readFloat32 expected i)).toFloat32.toBits)
  checkExactBF16 "embed-gather-bf16" (← outputB.copyTo stream) rounded (rows * hidden)

private def gateCast (dir : String) (stream : Cuda.Stream) : IO Unit := do
  let count := rows * hidden
  let x ← uploadF32 dir "cast_x.8x256" count stream
  let narrowed ← allocBF16 count
  let toBF16 ← castF32ToBF16 stream x narrowed count.toUInt32
  toBF16.waitChecked "cast-f32-to-bf16"
  checkExactBF16 "cast-f32-to-bf16" (← narrowed.copyTo stream)
    (← loadFixture dir "cast_bf16.8x256" count) count
  let widened ← allocF32 count
  let toF32 ← castBF16ToF32 stream narrowed widened count.toUInt32
  toF32.waitChecked "cast-bf16-to-f32"
  checkExactF32 "cast-bf16-to-f32" (← widened.copyTo stream)
    (← loadFixture dir "cast_bf16.8x256" count) count

private def fixtureDirectory : IO String := do
  let some directory ← IO.getEnv "QWEN36_PRIMITIVE_FIXTURES"
    | LeanTest.fail "QWEN36_PRIMITIVE_FIXTURES is required"
  return directory

@[test]
def allDevicePrimitivesMatchReference : IO Unit := do
  let dir ← fixtureDirectory
  let stream ← Cuda.Stream.default
  gateRmsNormF32 dir stream
  gateRmsNormBF16 dir stream
  gateGatedRmsNormF32 dir stream
  gateGatedRmsNormBF16 dir stream
  gateRope dir stream
  gateConv dir stream
  gateL2Norm dir stream
  gateSilu dir stream
  gateSwiglu dir stream
  gateEmbedding dir stream
  gateCast dir stream

end Qwen36PrimitivesGate
