//! Emission of the output tree.
//!
//!   model.h        every dimension as a compile-time constant
//!   weights.h      the weight table, resolved at COMPILE time: which bytes of
//!                  which safetensors file become which device pointer.  The
//!                  generated loader performs no name lookup and makes no
//!                  layout decision at run time.
//!   megakernel.cu  the kernel (see codegen.rs)
//!   runtime.cu     loader, allocation, decode loop, C ABI
//!   harness.py     the correctness gate and the benchmark
//!   Makefile, plan.txt

use crate::codegen::Gen;
use crate::hw::Hw;
use crate::ir::*;
use crate::layout::{layout, weights_h, EWeight};
use crate::plan::Plan;
use std::fmt::Write as _;
use std::fs;
use std::path::Path;

// ============================================================ host runtime
fn rope_code(m: &Model) -> String {
    // inv_freq, exactly as transformers computes it -- verified against the
    // reference tables by the generated harness (tests/test_rope).
    let mut s = String::new();
    let rd = m.rope.rotary_dim;
    let _ = writeln!(s, "static void mk_inv_freq(double* inv, double* attn_factor) {{");
    let _ = writeln!(s, "    const double base = {:.9};", m.rope.theta);
    let _ = writeln!(s, "    const int dim = {};", rd);
    let _ = writeln!(s, "    *attn_factor = 1.0;");
    let _ = writeln!(s, "    for (int i = 0; i < dim/2; ++i) inv[i] = 1.0 / pow(base, (double)(2*i)/dim);");
    match &m.rope.scaling {
        RopeScaling::None => {}
        RopeScaling::Linear { factor } => {
            let _ = writeln!(s, "    for (int i = 0; i < dim/2; ++i) inv[i] /= {:.9};", factor);
        }
        RopeScaling::Llama3 {
            factor,
            low_freq_factor,
            high_freq_factor,
            original_max_position,
        } => {
            let _ = writeln!(s, "    const double f = {:.9}, lo = {:.9}, hi = {:.9}, oc = {:.1};",
                factor, low_freq_factor, high_freq_factor, *original_max_position as f64);
            let _ = writeln!(s, "    const double lw = oc/lo, hw = oc/hi;");
            let _ = writeln!(s, "    for (int i = 0; i < dim/2; ++i) {{");
            let _ = writeln!(s, "        const double wl = 2.0*M_PI/inv[i];");
            let _ = writeln!(s, "        double v = (wl > lw) ? inv[i]/f : inv[i];");
            let _ = writeln!(s, "        if (!(wl < hw) && !(wl > lw)) {{");
            let _ = writeln!(s, "            const double sm = (oc/wl - lo)/(hi - lo);");
            let _ = writeln!(s, "            v = (1.0-sm)*v/f + sm*v;");
            let _ = writeln!(s, "        }}");
            let _ = writeln!(s, "        inv[i] = v;");
            let _ = writeln!(s, "    }}");
        }
        RopeScaling::Yarn {
            factor,
            beta_fast,
            beta_slow,
            original_max_position,
            attn_factor,
            truncate,
        } => {
            let af = if *attn_factor > 0.0 && (*attn_factor - 1.0).abs() > 1e-9 {
                *attn_factor as f64
            } else {
                0.0
            };
            let _ = writeln!(s, "    const double f = {:.9}, bf = {:.9}, bs = {:.9}, om = {:.1};",
                factor, beta_fast, beta_slow, *original_max_position as f64);
            let _ = writeln!(s, "    *attn_factor = {};",
                if af > 0.0 { format!("{:.9}", af) } else { "(f <= 1.0 ? 1.0 : 0.1*log(f) + 1.0)".into() });
            let _ = writeln!(s, "    double lowd = (dim*log(om/(bf*2.0*M_PI)))/(2.0*log(base));");
            let _ = writeln!(s, "    double highd = (dim*log(om/(bs*2.0*M_PI)))/(2.0*log(base));");
            if *truncate {
                let _ = writeln!(s, "    lowd = floor(lowd); highd = ceil(highd);");
            }
            let _ = writeln!(s, "    double lo = fmax(lowd, 0.0), hi = fmin(highd, (double)dim-1.0);");
            let _ = writeln!(s, "    if (lo == hi) hi += 0.001;");
            let _ = writeln!(s, "    for (int i = 0; i < dim/2; ++i) {{");
            let _ = writeln!(s, "        const double pf = pow(base, (double)(2*i)/dim);");
            let _ = writeln!(s, "        const double ex = 1.0/pf, in = 1.0/(f*pf);");
            let _ = writeln!(s, "        double ramp = ((double)i - lo)/(hi - lo);");
            let _ = writeln!(s, "        ramp = fmin(fmax(ramp, 0.0), 1.0);");
            let _ = writeln!(s, "        const double exf = 1.0 - ramp;");
            let _ = writeln!(s, "        inv[i] = in*(1.0-exf) + ex*exf;");
            let _ = writeln!(s, "    }}");
        }
    }
    let _ = writeln!(s, "}}");
    s
}

fn runtime_cu(m: &Model, p: &Plan, ws: &[EWeight]) -> String {
    let at = m.act_dtype.c_type();
    let mut s = String::new();
    let _ = writeln!(s, "// generated by mkc {} -- host runtime: loader, decode loop, C ABI", crate::VERSION);
    let _ = writeln!(s, r#"#include "kernel.h"
#include "weights.h"
#include "mk_api.h"
#include <cuda_runtime.h>
#include <cuda_fp8.h>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <cmath>
#include <string>
#include <vector>
#include <fcntl.h>
#include <unistd.h>

#define CK(x) do {{ cudaError_t e_=(x); if(e_!=cudaSuccess){{ \
  fprintf(stderr,"[mk] cuda: %s at %s:%d\n",cudaGetErrorString(e_),__FILE__,__LINE__); \
  return -1; }} }} while(0)
#define CKP(x) do {{ cudaError_t e_=(x); if(e_!=cudaSuccess){{ \
  fprintf(stderr,"[mk] cuda: %s at %s:%d\n",cudaGetErrorString(e_),__FILE__,__LINE__); \
  return nullptr; }} }} while(0)

// ---------------------------------------------------------------- convert
// The only shape change the loader may perform: read `nrows` rows of
// `rowelems` values in dtype `sdt`, write them at rows dst_row0 + j*dst_stride
// in dtype `ddt`.  Concatenation, gate/up interleaving and dtype casts are all
// instances of it, which is why the compiler can bake the whole load as a table.
// NB: every dtype the loader can encounter must appear in BOTH switches.  A
// missing case silently loads zeros -- an fp8 matrix that needed row
// interleaving did exactly that, and only the guard's weight probe caught it.
// Bytes per element, by dtype code.  Getting this wrong makes the loader read
// past a tensor: int32 (AWQ packing) is four bytes, not one.
static inline size_t mk_dt_size(int dt) {{
    switch (dt) {{
        case 0: case 7: return 4;
        case 1: case 2: return 2;
        case 8: return 8;
        default: return 1;
    }}
}}

__device__ __forceinline__ float mk_ld(const void* p, int dt, size_t i) {{
    switch (dt) {{
        case 0: return ((const float*)p)[i];
        case 1: return __half2float(((const __half*)p)[i]);
        case 2: return __bfloat162float(((const __nv_bfloat16*)p)[i]);
        case 3: return (float)((const unsigned char*)p)[i];
        case 4: return (float)((const signed char*)p)[i];
        case 5: return __half2float(__half(((const __nv_fp8_e4m3*)p)[i]));
        case 6: return __half2float(__half(((const __nv_fp8_e5m2*)p)[i]));
        case 7: return (float)((const int*)p)[i];
        default: return 0.f;
    }}
}}
__device__ __forceinline__ void mk_st(void* p, int dt, size_t i, float v) {{
    switch (dt) {{
        case 0: ((float*)p)[i] = v; break;
        case 1: ((__half*)p)[i] = __float2half(v); break;
        case 2: ((__nv_bfloat16*)p)[i] = __float2bfloat16(v); break;
        case 3: ((unsigned char*)p)[i] = (unsigned char)v; break;
        case 4: ((signed char*)p)[i] = (signed char)v; break;
        case 5: ((__nv_fp8_e4m3*)p)[i] = __nv_fp8_e4m3(v); break;
        case 6: ((__nv_fp8_e5m2*)p)[i] = __nv_fp8_e5m2(v); break;
        case 7: ((int*)p)[i] = (int)v; break;
        default: break;
    }}
}}
// ---------------------------------------------------------------- repack
// AWQ packs eight OUTPUT rows into one 32-bit word, in the order
// {{0,2,4,6,1,3,5,7}}, with k running down the rows of the stored tensor.  The
// canonical layout the gemv core reads is the transpose of that, two values per
// byte along k.  Doing the shuffle once at load time keeps it out of the inner
// loop and means one core serves AWQ and GPTQ alike.
__device__ __constant__ int MK_AWQ_ORDER[8] = {{0, 2, 4, 6, 1, 3, 5, 7}};

__global__ void k_awq_q(uint8_t* dst, const int* src, long long k0, long long nk,
                        long long rows, long long K,
                        long long dst_row0, long long dst_stride) {{
    const long long ncol = rows / 8, npair = nk / 2;
    for (long long i = (long long)blockIdx.x*blockDim.x + threadIdx.x; i < npair*ncol;
         i += (long long)gridDim.x*blockDim.x) {{
        const long long p = i / ncol, j = i - p*ncol;
        const unsigned lo = (unsigned)src[(2*p + 0)*ncol + j];
        const unsigned hi = (unsigned)src[(2*p + 1)*ncol + j];
        #pragma unroll
        for (int t = 0; t < 8; ++t) {{
            const long long n = dst_row0 + (8*j + MK_AWQ_ORDER[t])*dst_stride;
            const unsigned a = (lo >> (4*t)) & 0xFu, b = (hi >> (4*t)) & 0xFu;
            dst[(size_t)n*(K/2) + (k0/2 + p)] = (uint8_t)(a | (b << 4));
        }}
    }}
}}

__global__ void k_awq_z(__half* dst, const int* src, long long g0, long long ng,
                        long long rows, long long NG,
                        long long dst_row0, long long dst_stride) {{
    const long long ncol = rows / 8;
    for (long long i = (long long)blockIdx.x*blockDim.x + threadIdx.x; i < ng*ncol;
         i += (long long)gridDim.x*blockDim.x) {{
        const long long g = i / ncol, j = i - g*ncol;
        const unsigned w = (unsigned)src[g*ncol + j];
        #pragma unroll
        for (int t = 0; t < 8; ++t) {{
            const long long n = dst_row0 + (8*j + MK_AWQ_ORDER[t])*dst_stride;
            dst[(size_t)n*NG + (g0 + g)] = __float2half((float)((w >> (4*t)) & 0xFu));
        }}
    }}
}}

__global__ void k_transpose_scales(__half* dst, const void* src, int sdt,
                                   long long g0, long long ng,
                                   long long rows, long long NG,
                                   long long dst_row0, long long dst_stride) {{
    for (long long i = (long long)blockIdx.x*blockDim.x + threadIdx.x; i < ng*rows;
         i += (long long)gridDim.x*blockDim.x) {{
        const long long g = i / rows, n = i - g*rows;
        dst[(size_t)(dst_row0 + n*dst_stride)*NG + (g0 + g)] =
            __float2half(mk_ld(src, sdt, (size_t)g*rows + n));
    }}
}}

__global__ void k_convert(void* dst, const void* src, long long nrows, long long rowelems,
                          long long dst_row0, long long dst_stride, int sdt, int ddt,
                          long long repeat) {{
    const long long n = nrows * rowelems * repeat;
    for (long long i = (long long)blockIdx.x*blockDim.x + threadIdx.x; i < n;
         i += (long long)gridDim.x*blockDim.x) {{
        const long long d = i / rowelems, c = i - d*rowelems;   // destination row
        const long long r = d / repeat;                          // source row
        mk_st(dst, ddt, (size_t)(dst_row0 + d*dst_stride)*rowelems + c,
              mk_ld(src, sdt, (size_t)r*rowelems + c));
    }}
}}
"#);
    s.push_str(&rope_code(m));

    let _ = writeln!(s, r#"
struct MkCtx {{
    char*   arena = nullptr;
    LayerW* d_layers = nullptr;
    Globals g{{}};
    int     grid = 0, blocks_per_sm = 0, sms = 0, regs = 0;
    size_t  smem = 0;
    int     max_ctx = 0, max_len = 0;
    int     dev = 0;
    cudaStream_t stream = nullptr;
    float   last_ms = 0.f;
    cudaEvent_t ev0, ev1;
    std::string dir;
    void*   scratch = nullptr;
    void*   prof_buf = nullptr;
}};

static const size_t MK_STAGE = 256ull<<20;

// Load exactly one weight.  Factored out so the adversarial guard can zero a
// tensor, observe that the output moves, and put the real bytes back -- without
// which "is this weight read at all" is not a question that can be asked.
static int mk_load_one(MkCtx* c, int wi, char* hbuf, char* dbuf,
                       const std::vector<int>& fds, size_t* done) {{
    const size_t STAGE = MK_STAGE;
    {{
        const MkWeight& w = MK_WEIGHTS[wi];
        for (int pi = w.first; pi < w.first + w.n; ++pi) {{
            const MkPart& p = MK_PARTS[pi];
            const size_t srow = (size_t)p.rowelems * mk_dt_size(p.dtype);
            size_t rows_per_chunk = srow ? (STAGE / srow) : 1;
            if (rows_per_chunk == 0) rows_per_chunk = 1;
            for (size_t r0 = 0; r0 < p.nrows; r0 += rows_per_chunk) {{
                const size_t nr = (p.nrows - r0 < rows_per_chunk) ? (p.nrows - r0) : rows_per_chunk;
                const size_t nb = nr * srow;
                ssize_t got = pread(fds[p.file], hbuf, nb, (off_t)(p.off + r0*srow));
                if (got != (ssize_t)nb) {{ fprintf(stderr, "[mk] short read on %s (%zd/%zu)\n",
                                                  MK_FILES[p.file], got, nb); return -1; }}
                CK(cudaMemcpyAsync(dbuf, hbuf, nb, cudaMemcpyHostToDevice, c->stream));
                const long long drow0 = (long long)(p.dst_row0 + r0*p.repeat*p.dst_stride);
                const int blk_ = 256;
                if (p.xf) {{
                    const long long gr = 4096;
                    if (p.xf == 1)
                        k_awq_q<<<gr, blk_, 0, c->stream>>>(
                            (uint8_t*)(c->arena + w.dst_off), (const int*)dbuf,
                            (long long)r0, (long long)nr, (long long)(p.rowelems*8),
                            (long long)p.kdim,
                            (long long)p.dst_row0, (long long)p.dst_stride);
                    else if (p.xf == 2)
                        k_awq_z<<<gr, blk_, 0, c->stream>>>(
                            (__half*)(c->arena + w.dst_off), (const int*)dbuf,
                            (long long)r0, (long long)nr, (long long)(p.rowelems*8),
                            (long long)p.kdim,
                            (long long)p.dst_row0, (long long)p.dst_stride);
                    else
                        k_transpose_scales<<<gr, blk_, 0, c->stream>>>(
                            (__half*)(c->arena + w.dst_off), dbuf, p.dtype,
                            (long long)r0, (long long)nr, (long long)p.rowelems,
                            (long long)p.kdim,
                            (long long)p.dst_row0, (long long)p.dst_stride);
                }} else if (p.dtype == w.out_dtype && p.dst_stride == 1 && p.repeat == 1) {{
                    CK(cudaMemcpyAsync(c->arena + w.dst_off + (size_t)drow0*srow, dbuf, nb,
                                       cudaMemcpyDeviceToDevice, c->stream));
                }} else {{
                    const long long n = (long long)nr * (long long)p.rowelems * (long long)p.repeat;
                    const int blk = 256, gr = (int)std::min<long long>(65535, (n + blk - 1)/blk);
                    k_convert<<<gr, blk, 0, c->stream>>>(
                        c->arena + w.dst_off, dbuf, (long long)nr, (long long)p.rowelems,
                        drow0, (long long)p.dst_stride, p.dtype, w.out_dtype,
                        (long long)p.repeat);
                }}
                CK(cudaStreamSynchronize(c->stream));
                if (done) *done += nb;
            }}
        }}
    }}
    return 0;
}}

static int mk_open_files(MkCtx* c, std::vector<int>& fds) {{
    fds.assign(MK_NFILES, -1);
    for (int i = 0; i < MK_NFILES; ++i) {{
        std::string path = c->dir + "/" + MK_FILES[i];
        fds[i] = open(path.c_str(), O_RDONLY);
        if (fds[i] < 0) {{ fprintf(stderr, "[mk] cannot open %s\n", path.c_str()); return -1; }}
    }}
    return 0;
}}

// Built once at create time, and rebuilt by the guard after it has zeroed them
// to check that the rotation is really applied.
static int mk_build_rope(MkCtx* c) {{
    std::vector<double> inv(M::RD/2); double af = 1.0;
    mk_inv_freq(inv.data(), &af);
    std::vector<{at}> hc((size_t)M::MAXCTX*(M::RD/2)), hs(hc.size());
    for (int p = 0; p < M::MAXCTX; ++p)
        for (int i = 0; i < M::RD/2; ++i) {{
            const double a = (double)p * inv[i];
            hc[(size_t)p*(M::RD/2)+i] = ({at})(float)(cos(a)*af);
            hs[(size_t)p*(M::RD/2)+i] = ({at})(float)(sin(a)*af);
        }}
    CK(cudaMemcpy((void*)c->g.rt.cosd, hc.data(), hc.size()*sizeof({at}), cudaMemcpyHostToDevice));
    CK(cudaMemcpy((void*)c->g.rt.sind, hs.data(), hs.size()*sizeof({at}), cudaMemcpyHostToDevice));
    return 0;
}}

extern "C" int mk_rope_zero(MkCtx* c) {{
    const size_t n = (size_t)M::MAXCTX*(M::RD/2)*sizeof({at});
    CK(cudaMemset((void*)c->g.rt.cosd, 0, n));
    CK(cudaMemset((void*)c->g.rt.sind, 0, n));
    return 0;
}}
extern "C" int mk_rope_rebuild(MkCtx* c) {{ return mk_build_rope(c); }}

static int mk_load_weights(MkCtx* c) {{
    char* hbuf = nullptr; char* dbuf = nullptr;
    CK(cudaMallocHost(&hbuf, MK_STAGE));
    CK(cudaMalloc(&dbuf, MK_STAGE));
    std::vector<int> fds;
    if (mk_open_files(c, fds) != 0) return -1;
    size_t done = 0;
    for (int wi = 0; wi < MK_NWEIGHTS; ++wi) {{
        if (mk_load_one(c, wi, hbuf, dbuf, fds, &done) != 0) return -1;
        if ((wi & 63) == 0)
            fprintf(stderr, "\r[mk] loading %5.1f%%  %s        ",
                    100.0*wi/MK_NWEIGHTS, MK_WEIGHTS[wi].role);
    }}
    fprintf(stderr, "\r[mk] loaded %.2f GB from %d files            \n", done/1e9, MK_NFILES);
    for (int f : fds) close(f);
    cudaFreeHost(hbuf); cudaFree(dbuf);
    return 0;
}}
"#);

    // ---- LayerW filling ------------------------------------------------
    // Driven by `quant::parts`, so a new weight format needs no edit here.
    let has = |r: &str| ws.iter().any(|w| w.role == format!("l0.{}", r));
    let mut fill = String::new();
    let put = |fill: &mut String, role: &str, ty: &str| {
        let _ = writeln!(fill, "        h[L].{r} = ({ty}*)(c->arena + OFF_L_{r}[L]);", r = role, ty = ty);
    };
    let put_mat = |fill: &mut String, role: &str, q: &Quant| {
        for p in crate::quant::parts(q, m.act_dtype) {
            let f = format!("{}_{}", role, p.suffix);
            let _ = writeln!(fill, "        h[L].{f} = (const {ty}*)(c->arena + OFF_L_{f}[L]);",
                             f = f, ty = p.ctype);
        }
    };
    put(&mut fill, "attn_norm", "const float");
    put_mat(&mut fill, "qkv", &m.q_attn);
    if has("qkv_b") { put(&mut fill, "qkv_b", "const float"); }
    if has("q_norm") {
        put(&mut fill, "q_norm", "const float");
        put(&mut fill, "k_norm", "const float");
    }
    if has("sinks") { put(&mut fill, "sinks", "const float"); }
    put_mat(&mut fill, "o", &m.q_attn);
    if has("o_b") { put(&mut fill, "o_b", "const float"); }
    if has("post_attn_norm") { put(&mut fill, "post_attn_norm", "const float"); }
    put(&mut fill, "ffn_norm", "const float");
    if has("post_ffn_norm") { put(&mut fill, "post_ffn_norm", "const float"); }
    match &m.ffn {
        Ffn::Dense { .. } => {
            put_mat(&mut fill, "gu", &m.q_ffn);
            put_mat(&mut fill, "dn", &m.q_ffn);
        }
        Ffn::Moe { cfg, .. } => {
            put(&mut fill, "router_w", &format!("const {}", at));
            if has("router_b") { put(&mut fill, "router_b", "const float"); }
            else { let _ = writeln!(fill, "        h[L].router_b = nullptr;"); }
            if cfg.router_correction_bias { put(&mut fill, "router_cb", "const float"); }
            if let Ffn::Moe { shared_intermediate: si, .. } = &m.ffn {
                if *si > 0 {
                    put_mat(&mut fill, "sgu", &m.q_ffn);
                    put_mat(&mut fill, "sdn", &m.q_ffn);
                    if has("sgate_w") { put(&mut fill, "sgate_w", &format!("const {}", at)); }
                }
            }
            put_mat(&mut fill, "egu", &m.q_ffn);
            put_mat(&mut fill, "edn", &m.q_ffn);
            if has("egu_b") {
                put(&mut fill, "egu_b", "const float");
                put(&mut fill, "edn_b", "const float");
            } else {
                let _ = writeln!(fill, "        h[L].egu_b = nullptr; h[L].edn_b = nullptr;");
            }
        }
    }
    let _ = writeln!(
        fill,
        "        h[L].kcache = kv + (size_t)(2*L+0)*M::NKV*c->max_ctx*M::HD;\n        \
         h[L].vcache = kv + (size_t)(2*L+1)*M::NKV*c->max_ctx*M::HD;"
    );

    let _ = writeln!(s, r#"
static MkCtx* mk_create_impl(const char* dir, int max_ctx, int max_len, int device, int fake);

// Timing does not depend on what the weights ARE, only on their layout and
// size, so a verification pass can fill the arena with a pattern instead of
// reading 61 GB from disk.  That is what makes `mkc build --verify` cheap
// enough to be worth having.
extern "C" MkCtx* mk_create(const char* dir, int max_ctx, int max_len, int device) {{
    return mk_create_impl(dir, max_ctx, max_len, device, 0);
}}
extern "C" MkCtx* mk_create_fake(int max_ctx, int max_len, int device) {{
    return mk_create_impl(".", max_ctx, max_len, device, 1);
}}
static MkCtx* mk_create_impl(const char* dir, int max_ctx, int max_len, int device, int fake) {{
    MkCtx* c = new MkCtx();
    c->dir = dir; c->dev = device;
    c->max_ctx = max_ctx > 0 ? max_ctx : M::MAXCTX;
    if (c->max_ctx > M::MAXCTX) {{
        fprintf(stderr, "[mk] compiled for MAXCTX=%d, asked for %d\n", M::MAXCTX, c->max_ctx);
        return nullptr;
    }}
    // MAXCTX is compile-time: the kv cache is a fixed allocation and the plan
    // was priced for it.  `max_ctx` is accepted so a caller can ASK for less and
    // be told it gets what was compiled, not silently given a smaller cache.
    if (max_ctx > 0 && max_ctx > M::MAXCTX)
        fprintf(stderr, "[mk] asked for context %d, compiled for %d\n", max_ctx, M::MAXCTX);
    c->max_ctx = M::MAXCTX;
    c->max_len = max_len > 0 ? max_len : M::MAXCTX;
    CKP(cudaSetDevice(device));
    int coop = 0;
    cudaDeviceGetAttribute(&coop, cudaDevAttrCooperativeLaunch, device);
    if (!coop) {{ fprintf(stderr, "[mk] device does not support cooperative launch\n"); return nullptr; }}
    cudaDeviceProp pr; CKP(cudaGetDeviceProperties(&pr, device));
    if (strcmp(pr.name, M::PLANNED_FOR) != 0)
        fprintf(stderr, "[mk] WARNING: planned for '%s', running on '%s' -- the "
                        "schedule was priced against the other card's calibration\n",
                M::PLANNED_FOR, pr.name);
    c->sms = pr.multiProcessorCount;
    CKP(cudaStreamCreate(&c->stream));
    CKP(cudaEventCreate(&c->ev0)); CKP(cudaEventCreate(&c->ev1));

    CKP(cudaMalloc(&c->arena, MK_ARENA_BYTES));
    if (fake) {{
        // a pattern that is finite in every dtype and gives the router a spread
        // of logits, so the top-k picks k distinct experts as it would for real
        CKP(cudaMemset(c->arena, 0x3c, MK_ARENA_BYTES));
    }} else if (mk_load_weights(c) != 0) {{
        return nullptr;
    }}

    // ---- kv cache and scratch
    const size_t kvel = (size_t)M::NL*2*M::NKV*c->max_ctx*M::HD;
    {at}* kv = nullptr; CKP(cudaMalloc(&kv, kvel*sizeof({at})));
    CKP(cudaMemset(kv, 0, kvel*sizeof({at})));

    const size_t f_x = M::H, f_q = M::QD, f_k = M::KVD, f_a = M::QD;
    const size_t f_ps = (size_t)M::NQ*M::SPLITS*M::HD, f_pm = (size_t)M::NQ*M::SPLITS*2;
    const size_t f_act = {actsz};
    const size_t f_gate = (M::NEXP ? M::NEXP : 1);
    const size_t f_tmp = M::H;
    const size_t f_log = M::VOCAB;
    const size_t f_cs = (size_t)M::MAXCTX*(M::RD/2);
    char* sc = nullptr;
    // `take` rounds every allocation up to 256 bytes, so the slack has to cover
    // one rounding PER allocation, not a fixed 4 kB.  It did not, and the
    // eighteenth `take` ran off the end into the weight arena: the guard caught
    // it as NaN logits.  MK_SCRATCH_SLOTS is deliberately larger than the number
    // of takes below, and the assertion after them says so out loud.
    const size_t scbytes = f_x*sizeof({at}) + (f_q+f_k+f_a+f_ps+f_pm+f_act+f_gate+f_tmp+f_log)*4
                         + 2*f_cs*sizeof({at}) + (size_t)c->max_len*4 + MK_PROF_SLOTS*8
                         + 256*MK_SCRATCH_SLOTS;
    CKP(cudaMalloc(&sc, scbytes));
    CKP(cudaMemset(sc, 0, scbytes));
    c->scratch = sc;
    char* q = sc;
    auto take = [&](size_t bytes) {{ char* r = q; q += ((bytes + 255)&~255ull); return r; }};
    c->g.rt.x     = ({at}*)take(f_x*sizeof({at}));
    c->g.rt.qraw  = (float*)take(f_q*4);
    c->g.rt.kraw  = (float*)take(f_k*4);
    c->g.rt.attno = (float*)take(f_a*4);
    c->g.rt.psum  = (float*)take(f_ps*4);
    c->g.rt.pml   = (float*)take(f_pm*4);
    c->g.rt.act   = (float*)take(f_act*4);
    c->g.rt.gate  = (float*)take(f_gate*4);
    c->g.rt.tmp   = (float*)take(f_tmp*4);
    c->g.rt.sgate = (float*)take(64);
    c->g.logits   = (float*)take(f_log*4);
    {at}* cosd    = ({at}*)take(f_cs*sizeof({at}));
    {at}* sind    = ({at}*)take(f_cs*sizeof({at}));
    c->g.tokens   = (int*)take((size_t)c->max_len*4);
    c->g.dpos     = (int*)take(64);
    c->g.dargmax  = (unsigned long long*)take(64);
    c->prof_buf   = take(MK_PROF_SLOTS*8);
    c->g.prof     = nullptr;   // off unless mk_prof_enable
    if ((size_t)(q - sc) > scbytes) {{
        fprintf(stderr, "[mk] scratch overflow: %zu > %zu -- raise MK_SCRATCH_SLOTS\n",
                (size_t)(q - sc), scbytes);
        return nullptr;
    }}
    c->g.rt.cosd = cosd; c->g.rt.sind = sind;

    // ---- rope tables, in the activation dtype (transformers returns cos/sin
    // cast to the hidden dtype, and matching that keeps the gate meaningful)
    if (mk_build_rope(c) != 0) return nullptr;

    // ---- layer table
    {{
        std::vector<LayerW> h(M::NL);
        for (int L = 0; L < M::NL; ++L) {{
{fill}        }}
        CKP(cudaMalloc(&c->d_layers, M::NL*sizeof(LayerW)));
        CKP(cudaMemcpy(c->d_layers, h.data(), M::NL*sizeof(LayerW), cudaMemcpyHostToDevice));
    }}
    c->g.layers  = c->d_layers;
    c->g.fnorm   = (const float*)(c->arena + OFF_final_norm);
    c->g.embed   = (const {at}*)(c->arena + OFF_embed);
    c->g.unembed = M::TIED_EMBED ? c->g.embed : (const {at}*)(c->arena + OFF_lm_head);
    c->g.greedy  = 0;

    // ---- grid: exactly the resident set, from the occupancy API.  A
    // persistent kernel with grid barriers deadlocks if a block is not resident,
    // so this is never a guess.
    c->smem = SMEM_BYTES;
    CKP(cudaFuncSetAttribute(mk_megakernel, cudaFuncAttributeMaxDynamicSharedMemorySize, (int)c->smem));
    CKP(cudaOccupancyMaxActiveBlocksPerMultiprocessor(&c->blocks_per_sm, mk_megakernel, M::NT, c->smem));
    cudaFuncAttributes fa; CKP(cudaFuncGetAttributes(&fa, mk_megakernel));
    c->regs = fa.numRegs;
    if (c->blocks_per_sm < 1) {{
        fprintf(stderr, "[mk] kernel is not resident at NT=%d smem=%zu (regs=%d)\n",
                M::NT, c->smem, c->regs);
        return nullptr;
    }}
    c->grid = c->blocks_per_sm * c->sms;
    fprintf(stderr, "[mk] grid=%d (%d/SM x %d SM) NT=%d smem=%zu regs=%d\n",
            c->grid, c->blocks_per_sm, c->sms, M::NT, c->smem, c->regs);
    return c;
}}

extern "C" void mk_free(MkCtx* c) {{
    if (!c) return;
    cudaFree(c->arena); cudaFree(c->d_layers); cudaFree(c->scratch);
    cudaStreamDestroy(c->stream); delete c;
}}

extern "C" int mk_reset(MkCtx* c) {{
    int z = 0; CK(cudaMemcpy(c->g.dpos, &z, 4, cudaMemcpyHostToDevice));
    unsigned long long zz = 0; CK(cudaMemcpy(c->g.dargmax, &zz, 8, cudaMemcpyHostToDevice));
    return 0;
}}

// `n` is also the prompt length: greedy decoding appends after it and never
// overwrites it, so a caller may run the whole prefill with greedy on.
extern "C" int mk_set_tokens(MkCtx* c, const int* ids, int n) {{
    if (n > c->max_len) return -1;
    CK(cudaMemcpy(c->g.tokens, ids, (size_t)n*4, cudaMemcpyHostToDevice));
    c->g.n_prompt = n;
    return 0;
}}

extern "C" int mk_set_prompt_len(MkCtx* c, int n) {{ c->g.n_prompt = n; return 0; }}

extern "C" int mk_set_pos(MkCtx* c, int pos) {{
    CK(cudaMemcpy(c->g.dpos, &pos, 4, cudaMemcpyHostToDevice));
    return 0;
}}

// The kv cache and the token buffer are fixed allocations; running past either
// would write into whatever follows.  Checked OUTSIDE the timed region: reading
// the device position is a blocking copy, and putting it between the events
// would charge its latency to the kernel.
static int mk_check_room(MkCtx* c, int n) {{
    int p0 = 0; CK(cudaMemcpy(&p0, c->g.dpos, 4, cudaMemcpyDeviceToHost));
    if (p0 + n > M::MAXCTX) {{
        fprintf(stderr, "[mk] run would reach position %d, kv cache holds %d\n", p0 + n, M::MAXCTX);
        return -1;
    }}
    if (p0 + n > c->max_len) {{
        fprintf(stderr, "[mk] run would reach position %d, token buffer holds %d\n", p0 + n, c->max_len);
        return -1;
    }}
    return 0;
}}

// Cooperative, because a persistent kernel with a grid-wide rendezvous
// deadlocks unless every block is resident, and that is the guarantee a
// cooperative launch buys.  The rendezvous itself is `grid.sync()`: a
// hand-rolled counting barrier was tried and measured 0.2-0.5 us per barrier
// SLOWER, because every block's arrival serialises on one contended cache line
// where cooperative groups uses a tree (see calib/bar_probe.cu).
static int mk_launch(MkCtx* c, int n, int greedy) {{
    c->g.greedy = greedy;
    void* args[] = {{ (void*)&c->g }};
    for (int i = 0; i < n; ++i)
        CK(cudaLaunchCooperativeKernel((void*)mk_megakernel, c->grid, M::NT, args, c->smem, c->stream));
    return 0;
}}

// `n` decode steps with no host round trip: position, sampling and the token
// buffer all live on the device.
extern "C" int mk_run(MkCtx* c, int n, int greedy) {{
    if (mk_check_room(c, n) != 0) return -1;
    CK(cudaEventRecord(c->ev0, c->stream));
    if (mk_launch(c, n, greedy) != 0) return -1;
    CK(cudaEventRecord(c->ev1, c->stream));
    CK(cudaStreamSynchronize(c->stream));
    CK(cudaEventElapsedTime(&c->last_ms, c->ev0, c->ev1));
    return 0;
}}

extern "C" int mk_logits(MkCtx* c, float* out) {{
    CK(cudaMemcpy(out, c->g.logits, (size_t)M::VOCAB*4, cudaMemcpyDeviceToHost));
    return 0;
}}
extern "C" int mk_tokens(MkCtx* c, int* out, int n) {{
    CK(cudaMemcpy(out, c->g.tokens, (size_t)n*4, cudaMemcpyDeviceToHost));
    return 0;
}}
extern "C" int mk_pos(MkCtx* c) {{
    int p = 0; cudaMemcpy(&p, c->g.dpos, 4, cudaMemcpyDeviceToHost); return p;
}}
extern "C" double mk_last_ms(MkCtx* c) {{ return c->last_ms; }}
extern "C" int mk_vocab(MkCtx*) {{ return M::VOCAB; }}
extern "C" int mk_grid(MkCtx* c) {{ return c->grid; }}
extern "C" int mk_regs(MkCtx* c) {{ return c->regs; }}
extern "C" long long mk_smem(MkCtx* c) {{ return (long long)c->smem; }}
extern "C" int mk_maxctx(MkCtx*) {{ return M::MAXCTX; }}
extern "C" int mk_nlayers(MkCtx*) {{ return M::NL; }}
extern "C" int mk_hidden(MkCtx*) {{ return M::H; }}
// --- introspection, for the adversarial guard -------------------------
// The guard needs to be able to corrupt a weight and check the output moves,
// which is the only cheap test that a kernel really read what it claims to.
extern "C" long long mk_arena_bytes(MkCtx*) {{ return (long long)MK_ARENA_BYTES; }}
// The per-stage timeline the kernel wrote: nanosecond marks, one per barrier.
extern "C" int mk_prof(MkCtx* c, unsigned long long* out, int n) {{
    if (n > MK_PROF_SLOTS) n = MK_PROF_SLOTS;
    CK(cudaMemcpy(out, c->g.prof, (size_t)n*8, cudaMemcpyDeviceToHost));
    return n;
}}
extern "C" int mk_prof_enable(MkCtx* c, int on) {{
    c->g.prof = on ? (unsigned long long*)c->prof_buf : nullptr; return 0;
}}
extern "C" int mk_prof_slots(MkCtx*) {{ return MK_PROF_SLOTS; }}
extern "C" int mk_stages_per_layer(MkCtx*) {{ return MK_STAGES_PER_LAYER; }}
extern "C" int mk_poke(MkCtx* c, long long off, const void* src, long long n) {{
    if (off < 0 || off + n > (long long)MK_ARENA_BYTES) return -1;
    CK(cudaMemcpy(c->arena + off, src, (size_t)n, cudaMemcpyHostToDevice));
    return 0;
}}
extern "C" int mk_peek(MkCtx* c, long long off, void* dst, long long n) {{
    if (off < 0 || off + n > (long long)MK_ARENA_BYTES) return -1;
    CK(cudaMemcpy(dst, c->arena + off, (size_t)n, cudaMemcpyDeviceToHost));
    return 0;
}}
extern "C" const char* const MK_STAGE_NAMES[];
extern "C" void* const MK_STAGE_FNS[];

// Time one stage as an ordinary kernel launch: `reps` back-to-back launches,
// cycling the layer so the weights are never warm in L2.
extern "C" int mk_bench_stage(MkCtx* c, int si, int reps, double* out_us) {{
    int n = 0; while (MK_STAGE_NAMES[n]) ++n;
    if (si < 0 || si >= n) return -1;
    void* fn = MK_STAGE_FNS[si];
    CK(cudaFuncSetAttribute((const void*)fn, cudaFuncAttributeMaxDynamicSharedMemorySize, (int)c->smem));
    cudaEvent_t a, b; CK(cudaEventCreate(&a)); CK(cudaEventCreate(&b));
    for (int i = 0; i < 4; ++i) {{
        int L = i % M::NL;
        void* args[] = {{ (void*)&c->g, (void*)&L }};
        CK(cudaLaunchKernel(fn, c->grid, M::NT, args, c->smem, c->stream));
    }}
    CK(cudaStreamSynchronize(c->stream));
    CK(cudaEventRecord(a, c->stream));
    for (int i = 0; i < reps; ++i) {{
        int L = i % M::NL;
        void* args[] = {{ (void*)&c->g, (void*)&L }};
        CK(cudaLaunchKernel(fn, c->grid, M::NT, args, c->smem, c->stream));
    }}
    CK(cudaEventRecord(b, c->stream));
    CK(cudaStreamSynchronize(c->stream));
    float ms = 0; CK(cudaEventElapsedTime(&ms, a, b));
    *out_us = (double)ms * 1000.0 / reps;
    cudaEventDestroy(a); cudaEventDestroy(b);
    return 0;
}}
extern "C" int mk_nstages(MkCtx*) {{ int n = 0; while (MK_STAGE_NAMES[n]) ++n; return n; }}
extern "C" const char* mk_stage_name(MkCtx*, int i) {{ return MK_STAGE_NAMES[i]; }}
extern "C" int mk_nweights(MkCtx*) {{ return MK_NWEIGHTS; }}
extern "C" int mk_zero_weight(MkCtx* c, int i) {{
    if (i < 0 || i >= MK_NWEIGHTS) return -1;
    CK(cudaMemset(c->arena + MK_WEIGHTS[i].dst_off, 0, (size_t)MK_WEIGHTS[i].bytes));
    return 0;
}}
extern "C" int mk_reload_weight(MkCtx* c, int i) {{
    if (i < 0 || i >= MK_NWEIGHTS) return -1;
    char* hbuf = nullptr; char* dbuf = nullptr;
    CK(cudaMallocHost(&hbuf, MK_STAGE));
    CK(cudaMalloc(&dbuf, MK_STAGE));
    std::vector<int> fds;
    int rc = mk_open_files(c, fds);
    if (rc == 0) rc = mk_load_one(c, i, hbuf, dbuf, fds, nullptr);
    for (int f : fds) if (f >= 0) close(f);
    cudaFreeHost(hbuf); cudaFree(dbuf);
    return rc;
}}
extern "C" const char* mk_weight_role(MkCtx*, int i) {{
    return (i >= 0 && i < MK_NWEIGHTS) ? MK_WEIGHTS[i].role : nullptr;
}}
extern "C" long long mk_weight_off(MkCtx*, int i) {{
    return (i >= 0 && i < MK_NWEIGHTS) ? (long long)MK_WEIGHTS[i].dst_off : -1;
}}
extern "C" long long mk_weight_bytes(MkCtx*, int i) {{
    return (i >= 0 && i < MK_NWEIGHTS) ? (long long)MK_WEIGHTS[i].bytes : -1;
}}
extern "C" int mk_hidden_state(MkCtx* c, float* out) {{
    std::vector<{at}> h(M::H);
    CK(cudaMemcpy(h.data(), c->g.rt.x, M::H*sizeof({at}), cudaMemcpyDeviceToHost));
    for (int i = 0; i < M::H; ++i) out[i] = (float)h[i];
    return 0;
}}
"#,
        at = at,
        // The planner already worked out how many activation floats the widest
        // FFN stage needs -- a shared expert can be wider than all top_k routed
        // ones put together, and recomputing it here got that wrong.  Ask it.
        actsz = format!("(size_t){}", p.scratch.act_elems.max(1)),
        fill = fill
    );
    s
}

fn mk_api_h() -> String {
    r#"// generated by mkc -- C ABI for the megakernel runtime
#pragma once
#ifdef __cplusplus
extern "C" {
#endif
typedef struct MkCtx MkCtx;
MkCtx* mk_create(const char* model_dir, int max_ctx, int max_len, int device);
MkCtx* mk_create_fake(int max_ctx, int max_len, int device);
void   mk_free(MkCtx*);
int    mk_reset(MkCtx*);
int    mk_set_tokens(MkCtx*, const int* ids, int n);
int    mk_set_prompt_len(MkCtx*, int n);
int    mk_set_pos(MkCtx*, int pos);
int    mk_run(MkCtx*, int nsteps, int greedy);
int    mk_logits(MkCtx*, float* out);
int    mk_tokens(MkCtx*, int* out, int n);
int    mk_pos(MkCtx*);
double mk_last_ms(MkCtx*);
int    mk_vocab(MkCtx*);
int    mk_grid(MkCtx*);
int    mk_regs(MkCtx*);
long long mk_smem(MkCtx*);
int    mk_maxctx(MkCtx*);
int    mk_nlayers(MkCtx*);
int    mk_hidden(MkCtx*);
int    mk_hidden_state(MkCtx*, float* out);
int    mk_prof(MkCtx*, unsigned long long* out, int n);
int    mk_prof_enable(MkCtx*, int on);
int    mk_prof_slots(MkCtx*);
int    mk_stages_per_layer(MkCtx*);
long long mk_arena_bytes(MkCtx*);
int    mk_poke(MkCtx*, long long off, const void* src, long long n);
int    mk_peek(MkCtx*, long long off, void* dst, long long n);
int    mk_bench_stage(MkCtx*, int si, int reps, double* out_us);
int    mk_nstages(MkCtx*);
const char* mk_stage_name(MkCtx*, int i);
int    mk_rope_zero(MkCtx*);
int    mk_rope_rebuild(MkCtx*);
int    mk_nweights(MkCtx*);
int    mk_zero_weight(MkCtx*, int i);
int    mk_reload_weight(MkCtx*, int i);
const char* mk_weight_role(MkCtx*, int i);
long long mk_weight_off(MkCtx*, int i);
long long mk_weight_bytes(MkCtx*, int i);
#ifdef __cplusplus
}
#endif
"#
    .to_string()
}

/// A standalone decode-timing driver, so `mkc build --verify` can rank
/// candidates without Python and without reading the checkpoint.
fn mkbench_cpp() -> String {
    r##"// generated by mkc -- decode timing on synthetic weights
#include "mk_api.h"
#include <cstdio>
#include <cstdlib>
#include <vector>
int main(int argc, char** argv) {
    const int ctx    = argc > 1 ? atoi(argv[1]) : 1024;
    const int steps  = argc > 2 ? atoi(argv[2]) : 64;
    const int device = argc > 3 ? atoi(argv[3]) : 0;
    MkCtx* c = mk_create_fake(0, ctx + steps + 8, device);
    if (!c) { fprintf(stderr, "create failed\n"); return 1; }
    std::vector<int> ids(ctx + steps + 1);
    for (size_t i = 0; i < ids.size(); ++i) ids[i] = (int)((i * 2654435761u) % (unsigned)mk_vocab(c));
    mk_reset(c);
    if (mk_set_tokens(c, ids.data(), (int)ids.size()) != 0) return 1;
    if (mk_run(c, ctx, 0) != 0) return 1;                 // prefill
    // N-vs-1 differencing cancels the first step's cold caches, and the best of
    // three cancels a neighbour: a single sample here has picked the wrong
    // schedule before.
    double best = 1e30;
    for (int rep = 0; rep < 3; ++rep) {
        mk_set_pos(c, ctx); if (mk_run(c, 1, 0) != 0) return 1;
        const double t1 = mk_last_ms(c);
        mk_set_pos(c, ctx); if (mk_run(c, steps, 0) != 0) return 1;
        const double tN = mk_last_ms(c);
        const double per = (tN - t1) / (steps - 1);
        if (per > 0 && per < best) best = per;
    }
    printf("%.6f\n", best);                               // ms per decode token
    mk_free(c);
    return 0;
}
"##
    .to_string()
}

fn makefile(_m: &Model, arch: &str, inc: &str) -> String {
    format!(r#"# generated by mkc
# NB: the variable is MKARCH, not ARCH -- the module environments on HPC systems
# export ARCH=x86_64, which nvcc then rejects.
NVCC    ?= nvcc
MKARCH  ?= {arch}
MKINC   ?= {inc}
# --use_fast_math is deliberately OFF: it degrades expf/rsqrtf enough to move
# logits, and buys nothing on a kernel that is memory bound.
# -cudart shared: the .so is dlopen'd next to PyTorch, which has its own
# CUDA runtime; two static runtimes in one process is asking for trouble.
CFLAGS  = -O3 -std=c++17 -arch=$(MKARCH) -I$(MKINC) -I. -lineinfo -Xcompiler -fPIC -cudart shared
CFLAGS += -Xptxas -v

# The runtime headers are prerequisites.  Leaving them out is the classic way to
# "validate" a kernel rewrite that was never compiled: the object is stale and
# the .so silently keeps the old code.
MKHDRS  = $(wildcard $(MKINC)/mk/*.cuh)

all: libmk.so

libmk.so: megakernel.o stages.o runtime.o
	$(NVCC) $(CFLAGS) -shared -o $@ $^

megakernel.o: megakernel.cu stages.cuh kernel.h model.h $(MKHDRS)
	$(NVCC) $(CFLAGS) -c -o $@ $< 2> ptxas.log; cat ptxas.log

stages.o: stages.cu stages.cuh kernel.h model.h $(MKHDRS)
	$(NVCC) $(CFLAGS) -c -o $@ $<

runtime.o: runtime.cu kernel.h model.h weights.h mk_api.h $(MKHDRS)
	$(NVCC) $(CFLAGS) -c -o $@ $<

mkbench: mkbench.cpp libmk.so
	$(NVCC) -O2 -std=c++17 -I. -o $@ mkbench.cpp -L. -lmk -Xlinker -rpath -Xlinker $(CURDIR)

clean:
	rm -f *.o *.so ptxas.log mkbench
.PHONY: all clean
"#, arch = arch, inc = inc)
}

pub fn emit_all(m: &Model, p: &Plan, hw: &Hw, out: &Path, ctx: usize) -> Result<(), String> {
    fs::create_dir_all(out).map_err(|e| format!("{}: {}", out.display(), e))?;
    let g = Gen { m, p, hw, ctx };
    let (ws, arena) = layout(m);

    // Write only what changed.  `mkc build` re-emits the tree once per candidate
    // schedule, and most of the tree is the same every time; leaving mtimes
    // alone is what lets make rebuild the one translation unit that moved
    // instead of all of them.
    let w = |name: &str, body: String| -> Result<(), String> {
        let path = out.join(name);
        if fs::read_to_string(&path).map(|old| old == body).unwrap_or(false) {
            return Ok(());
        }
        fs::write(&path, body).map_err(|e| format!("{}: {}", name, e))
    };
    w("model.h", g.model_h())?;
    w("kernel.h", g.kernel_h())?;
    w("stages.cuh", g.stages_cuh())?;
    w("megakernel.cu", g.megakernel_cu())?;
    w("stages.cu", g.stages_cu())?;
    w("weights.h", weights_h(m, &ws, arena))?;
    w("runtime.cu", runtime_cu(m, p, &ws))?;
    w("mk_api.h", mk_api_h())?;
    let arch = format!("sm_{}{}", hw.sm_arch / 10, if hw.sm_arch == 90 { "0a".to_string() } else { format!("{}", hw.sm_arch % 10) });
    let inc = std::env::var("MKGEN_ROOT")
        .map(|r| format!("{}/runtime/include", r))
        .unwrap_or_else(|_| "../../runtime/include".into());
    w("mkbench.cpp", mkbench_cpp())?;
    w("Makefile", makefile(m, &arch, &inc))?;

    // machine-readable description of what was compiled, for the harness and
    // for the report; also the record that makes a build reproducible: the
    // model, the schedule, the machine model it was priced against and when
    // that was measured.
    let mut b = String::new();
    let _ = writeln!(b, "{{");
    let _ = writeln!(b, "  \"name\": \"{}\",", m.name);
    let _ = writeln!(b, "  \"arch\": \"{}\",", m.arch);
    let _ = writeln!(b, "  \"mkc_version\": \"{}\",", crate::VERSION);
    let _ = writeln!(b, "  \"device\": \"{}\",", hw.device);
    // which machine model this was compiled against: a number produced on one
    // node's calibration is not comparable with one produced on another's, and
    // this is where you find out
    let _ = writeln!(b, "  \"hw_calibrated_at\": \"{}\", \"hw_schema\": {},",
                     hw.calibrated_at, hw.schema);
    let _ = writeln!(b, "  \"hidden\": {}, \"layers\": {}, \"vocab\": {},", m.hidden, m.n_layers, m.vocab);
    let _ = writeln!(b, "  \"n_heads\": {}, \"n_kv_heads\": {}, \"head_dim\": {},", m.attn.n_heads, m.attn.n_kv_heads, m.attn.head_dim);
    let _ = writeln!(b, "  \"act_dtype\": \"{}\", \"q_ffn\": \"{}\",", m.act_dtype, m.q_ffn.tag());
    let _ = writeln!(b, "  \"moe\": {},", m.is_moe());
    // the same expression codegen emits as M::MAXCTX; the two used to disagree
    let _ = writeln!(b, "  \"ctx\": {}, \"max_ctx\": {},",
                     ctx, (ctx + (ctx / 2).max(512)).next_power_of_two().max(1024));
    let _ = writeln!(b, "  \"nt\": {}, \"grid_planned\": {}, \"attn_splits\": {},", p.nt, p.blocks, p.attn_splits);
    let _ = writeln!(b, "  \"arena_bytes\": {},", arena);
    let _ = writeln!(b, "  \"barriers_per_token\": {},", p.barriers_per_token);
    let _ = write!(b, "  \"stages\": [");
    for (i, st) in p.layer.iter().filter(|x| x.barrier_after).enumerate() {
        let _ = write!(b, "{}\"{}\"", if i > 0 { ", " } else { "" }, st.kind.short());
    }
    let _ = writeln!(b, "],");
    let _ = write!(b, "  \"stage_pred_us\": [");
    for (i, st) in p.layer.iter().filter(|x| x.barrier_after).enumerate() {
        let _ = write!(b, "{}{:.3}", if i > 0 { ", " } else { "" }, st.est_us);
    }
    let _ = writeln!(b, "],");
    let _ = write!(b, "  \"stage_bytes\": [");
    for (i, st) in p.layer.iter().filter(|x| x.barrier_after).enumerate() {
        let _ = write!(b, "{}{}", if i > 0 { ", " } else { "" }, st.bytes);
    }
    let _ = writeln!(b, "],");
    let _ = writeln!(b, "  \"lm_head_pred_us\": {:.3},", p.tail.iter().map(|s| s.est_us).sum::<f64>());
    let _ = writeln!(b, "  \"lm_head_bytes\": {},", p.tail.iter().map(|s| s.bytes).sum::<u64>());
    let _ = writeln!(b, "  \"predicted_ms\": {:.4},", p.est_ms);
    let rl = crate::report::roofline(m, ctx);
    let _ = writeln!(b, "  \"bytes_per_token\": {},", rl.total);
    let _ = writeln!(b, "  \"roofline_ms\": {:.4},", rl.ms_at(hw.stream_peak_gbs));
    // the same bytes charged at each format's own measured gemv ceiling
    let _ = writeln!(b, "  \"floor_ms\": {:.4},", rl.floor_ms(hw));
    let _ = writeln!(b, "  \"stream_peak_gbs\": {}", hw.stream_peak_gbs);
    let _ = writeln!(b, "}}");
    w("build.json", b)?;

    let mut txt = String::new();
    let _ = writeln!(txt, "{}", rl.render(hw.stream_peak_gbs));
    let _ = writeln!(txt, "{}", p.render(hw));
    w("plan.txt", txt)?;
    Ok(())
}
